#!/usr/bin/env python3
# Path: backend/scripts/suite_fingerprint.py
# File: suite_fingerprint.py
# Created: 2026-10-01
# Purpose: DWB-635 - attribute a published suite number to a known tree state,
#          including the gitignored inputs the suite reads, with any movement
#          during a run named per file and attributed to an owner.
# Caller: humans and agents publishing a suite result
# Callees: hashlib, git rev-parse (for the repo root and HEAD)
# Data In: a snapshot path, optionally a second path to diff against,
#          optionally --mine prefixes naming the caller's own files
# Data Out: a JSON snapshot, a digest line, and a per-file MINE/THEIRS delta
# Last Modified: 2026-10-01 (DWB-635: promoted from a session scratchpad)
"""A suite fingerprint scoped to what the suite READS, with a per-file manifest.

Instrument by Barry_DWB; promoted out of a session scratchpad under DWB-635.

WHY THIS RATHER THAN `git status --porcelain | md5`
---------------------------------------------------
Porcelain emits `<XY> <path>` and carries no file content. For a path already
reading ` M`, a content-only edit changes neither the status characters nor the
path, so the line is byte-identical and a status hash CANNOT MOVE. That is a
property of the output format, not an experiment. It is also why the regression
test for it must dirty an ALREADY-DIRTY file: a clean file enters a status and
so cannot discriminate, and a test using that fixture confirms the wrong answer.

A second instrument built the same night fixed the status blindness and was
blind to `.dwb/memory/**` instead, which is gitignored and therefore invisible
to BOTH `git status` and `git ls-files --others --exclude-standard`. The two
git views agree with each other there, so cross-checking one against the other
returns a consistent answer and confirms nothing. Hence: one instrument that
reads the filesystem directly, not two with complementary blind spots.

STATE THE ROLE BESIDE EVERY NUMBER
----------------------------------
    content hashes        DID IT CHANGE      has a forbidden region
    bytes and file counts DID IT HAVE INPUT  no forbidden region for change

Barry_DWB's term for the failure is ROLE DRIFT: a control sits beside real
evidence long enough that a later reader keeps the control and drops the
evidence, because the number was always there. The measured instance, from his
own output: `byte_count` read 6 before and 6 after a real content change,
because `x = 2` and `x = 3` are the same length. A byte count is a check that
the instrument HAD INPUT. It is not a change detector, and the labels are
printed on the lines themselves rather than in this docstring, because a role
that lives somewhere other than next to the number does not travel with it.

Usage:
    suite_fingerprint.py before.json [--mine PREFIX ...]
    suite_fingerprint.py before.json after.json [--mine PREFIX ...]
"""

import argparse
import hashlib
import json
import pathlib
import subprocess
import sys

# Scope derived from what the backend suite actually READS, each entry carrying
# the reason it is in scope. Deliberately wider than "my files": another lane's
# edit genuinely can change your result, and excluding it fails SILENTLY.
SCOPE = [
    ("backend/app", "**/*.py", "the code under test"),
    ("backend/tests", "**/*.py", "the tests themselves"),
    ("backend/scripts", "**/*.py", "imported by the DWB-620 repair tests"),
    (".dwb/memory", "*/*/memory.md", "the live corpus test_memory_format_dwb594 reads"),
    ("docs", "**/*.md", "test_doc_drift_dwb569 renders these"),
    (".claude", "*_playbook.md", "test_doc_drift_dwb569 compares against these"),
]

# Anything regenerated by a test run. Barry_DWB's version excluded these only by
# accident - its globs were `**/*.py` and `.pyc` lives in `__pycache__`, so they
# never matched. Made explicit here: a fingerprint that moves on every execution
# reports drift every time, gets labelled unreliable, and is then removed.
EXCLUDED_PARTS = {"__pycache__", ".pytest_cache", ".venv", "node_modules"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}


class ScopeRefused(Exception):
    """A root in scope matched nothing. Raised rather than printed, so a caller
    embedding this cannot mistake a refusal for a result."""


def repo_root(start: pathlib.Path | None = None) -> pathlib.Path:
    """The repo root, derived rather than hardcoded.

    The scratchpad original carried an absolute path to one machine's checkout,
    which is survivable for one night and fatal for a committed script.
    """
    start = start or pathlib.Path(__file__).resolve().parent
    proc = subprocess.run(
        ["git", "-C", str(start), "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
    )
    if proc.returncode == 0 and proc.stdout.strip():
        return pathlib.Path(proc.stdout.strip())
    # Fall back to walking up, so the tool still works outside a git checkout
    # rather than silently fingerprinting the wrong tree.
    for parent in [start, *start.parents]:
        if (parent / "backend").is_dir():
            return parent
    raise ScopeRefused(f"could not locate a repo root from {start}")


def _included(path: pathlib.Path) -> bool:
    if path.suffix in EXCLUDED_SUFFIXES:
        return False
    return not EXCLUDED_PARTS.intersection(path.parts)


def snapshot(repo: pathlib.Path, scope: list | None = None) -> dict:
    """Hash file CONTENT per file across the scope, refusing on an empty root.

    THE REFUSAL IS PER-ROOT, NOT ON THE TOTAL. The original checked only
    `file_count == 0`, so one root vanishing out of six passed silently while
    five populated roots carried the total. The root most likely to vanish is
    `.dwb/memory`, which no git view can see either, so nothing else would
    catch it. A zero in any one root is the hash-of-nothing failure one level
    down: perfectly stable, and it is the root that disappeared that you most
    needed to see.
    """
    scope = scope if scope is not None else SCOPE
    files: dict[str, str] = {}
    per_root: dict[str, int] = {}
    total_bytes = 0

    for root, pattern, why in scope:
        base = repo / root
        found = 0
        if base.is_dir():
            for p in sorted(base.glob(pattern)):
                if not p.is_file() or not _included(p):
                    continue
                data = p.read_bytes()
                files[str(p.relative_to(repo))] = hashlib.sha256(data).hexdigest()[:12]
                total_bytes += len(data)
                found += 1
        per_root[root] = found
        if found == 0:
            raise ScopeRefused(
                f"root '{root}' ({pattern}) matched 0 files - it is in scope "
                f"because {why}. A hash over a missing root is perfectly "
                f"stable and means nothing. Fix the path or remove the root "
                f"from SCOPE deliberately; do not let it pass as a total."
            )

    joined = "\n".join(f"{k} {v}" for k, v in sorted(files.items()))
    head = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
        capture_output=True,
        text=True,
    )
    return {
        "fingerprint": hashlib.sha256(joined.encode()).hexdigest()[:12],
        "file_count": len(files),
        "byte_count": total_bytes,
        # Surfaced rather than swallowed: an empty head from a failed git call
        # would otherwise look identical to a repo with no commits.
        "head": head.stdout.strip() if head.returncode == 0 else None,
        "head_error": None if head.returncode == 0 else head.stderr.strip(),
        "per_root": per_root,
        "files": files,
    }


def report(snap: dict, label: str) -> None:
    """Print the digest with each number's ROLE on the same line as the number."""
    print(f"{label}: fingerprint={snap['fingerprint']}   [DID IT CHANGE]")
    print(
        f"{' ' * len(label)}  files={snap['file_count']} "
        f"bytes={snap['byte_count']}   "
        f"[DID IT HAVE INPUT - not a change detector]"
    )
    print(f"{' ' * len(label)}  head={snap['head']}")
    if snap.get("head_error"):
        print(f"{' ' * len(label)}  head UNAVAILABLE: {snap['head_error']}")
    roots = " ".join(f"{k}={v}" for k, v in snap.get("per_root", {}).items())
    if roots:
        print(f"{' ' * len(label)}  per-root [DID EACH ROOT HAVE INPUT]: {roots}")


def _owned(path: str, mine: list[str]) -> bool:
    return any(path == m or path.startswith(m.rstrip("/") + "/") for m in mine)


def diff(before: dict, after: dict, mine: list[str] | None) -> None:
    b, a = before["files"], after["files"]
    changed = sorted(k for k in b.keys() | a.keys() if b.get(k) != a.get(k))
    if not changed:
        print("\nNO MOVEMENT in scope. The number is placeable.")
        return

    print(f"\nMOVED: {len(changed)} file(s). The hash says THAT; this says WHAT.")
    if mine is None:
        # The original defaulted to a hardcoded MINE set, so a stale list
        # silently reported every change as someone else's - a failure in the
        # FLATTERING direction, because "nothing of yours moved" is what the
        # reader wants to hear. Absent ownership is stated, never assumed.
        for k in changed:
            print(f"   UNATTRIBUTED {k}  {b.get(k, 'absent')} -> {a.get(k, 'absent')}")
        print(
            "\n  No --mine given, so NONE of these are attributed. This is not "
            "the same as 'nothing of yours moved'."
        )
    else:
        owned = [k for k in changed if _owned(k, mine)]
        others = [k for k in changed if not _owned(k, mine)]
        for k in owned:
            print(f"   MINE   {k}  {b.get(k, 'absent')} -> {a.get(k, 'absent')}")
        for k in others:
            print(f"   THEIRS {k}  {b.get(k, 'absent')} -> {a.get(k, 'absent')}")
        if others and not owned:
            print(
                "\n  Every change in scope belongs to someone else, so a result "
                "delta is NOT attributable to this lane."
            )
    print(
        "\n  A per-file delta names the FILE. The OWNER names the reason - do "
        "not report a delta as a cause."
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("before", help="snapshot to write, or to diff against")
    parser.add_argument("after", nargs="?", help="second snapshot; enables the diff")
    parser.add_argument(
        "--mine",
        action="append",
        metavar="PREFIX",
        help="a repo-relative path or directory prefix you own; repeatable. "
        "Omitted, every change is reported UNATTRIBUTED rather than THEIRS.",
    )
    args = parser.parse_args(argv)

    try:
        repo = repo_root()
        snap = snapshot(repo)
    except ScopeRefused as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 1

    if args.after is None:
        pathlib.Path(args.before).write_text(json.dumps(snap, indent=1))
        report(snap, "SNAPSHOT")
        return 0

    before = json.loads(pathlib.Path(args.before).read_text())
    pathlib.Path(args.after).write_text(json.dumps(snap, indent=1))
    report(before, "BEFORE")
    report(snap, "AFTER ")
    diff(before, snap, args.mine)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
