"""add force_initial_md and force_architecture_md to projects

Revision ID: 2e12eb5a0b56
Revises: 7b6d84a8227f
Create Date: 2026-03-28 12:17:32.926226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e12eb5a0b56'
down_revision: Union[str, None] = '7b6d84a8227f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('force_initial_md', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('force_architecture_md', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'force_architecture_md')
    op.drop_column('projects', 'force_initial_md')
    # ### end Alembic commands ###
