"""add jira fields

Revision ID: 31ae763f567d
Revises: b46dda6bec31
Create Date: 2026-04-01 12:42:26.242970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ae763f567d'
down_revision: Union[str, None] = 'b46dda6bec31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('jira_project_key', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_projects_jira_project_key'), 'projects', ['jira_project_key'], unique=False)
    op.add_column('tickets', sa.Column('jira_issue_key', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tickets_jira_issue_key'), 'tickets', ['jira_issue_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_jira_issue_key'), table_name='tickets')
    op.drop_column('tickets', 'jira_issue_key')
    op.drop_index(op.f('ix_projects_jira_project_key'), table_name='projects')
    op.drop_column('projects', 'jira_project_key')
    # ### end Alembic commands ###
