"""add epic_id to sprints

Revision ID: 6e5f7de537ff
Revises: fb05b4277a4d
Create Date: 2026-03-27 15:43:02.230399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5f7de537ff'
down_revision: Union[str, None] = 'fb05b4277a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('epic_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_sprints_epic_id'), 'sprints', ['epic_id'], unique=False)
    op.create_foreign_key(None, 'sprints', 'epics', ['epic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.drop_index(op.f('ix_sprints_epic_id'), table_name='sprints')
    op.drop_column('sprints', 'epic_id')
    # ### end Alembic commands ###
