"""add force_headers force_test_coverage force_test_run to projects

Revision ID: 7b6d84a8227f
Revises: ab105af9023f
Create Date: 2026-03-28 10:42:00.870536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6d84a8227f'
down_revision: Union[str, None] = 'ab105af9023f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('force_headers', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('projects', sa.Column('force_test_coverage', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('projects', sa.Column('force_test_run', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'force_test_run')
    op.drop_column('projects', 'force_test_coverage')
    op.drop_column('projects', 'force_headers')
    # ### end Alembic commands ###
