"""add jira_base_url to projects

Revision ID: 82531ae5bbcc
Revises: c59eb682137a
Create Date: 2026-03-27 13:26:20.780877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82531ae5bbcc'
down_revision: Union[str, None] = 'c59eb682137a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('jira_base_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'jira_base_url')
    # ### end Alembic commands ###
