"""add cascade delete to ticket child FKs

Revision ID: 85a791a9f79d
Revises: 055dd4b1a2dd
Create Date: 2026-04-16 09:41:21.969197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a791a9f79d'
down_revision: Union[str, None] = '055dd4b1a2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alerts_ibfk_3'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comments_ibfk_1'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('failure_records_ibfk_2'), 'failure_records', type_='foreignkey')
    op.create_foreign_key(None, 'failure_records', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('hook_sessions_ibfk_4'), 'hook_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'hook_sessions', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('status_history_ibfk_1'), 'status_history', type_='foreignkey')
    op.create_foreign_key(None, 'status_history', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('test_results_ibfk_3'), 'test_results', type_='foreignkey')
    op.create_foreign_key(None, 'test_results', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tracking_log_ibfk_1'), 'tracking_log', type_='foreignkey')
    op.create_foreign_key(None, 'tracking_log', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_log', type_='foreignkey')
    op.create_foreign_key(op.f('tracking_log_ibfk_1'), 'tracking_log', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.create_foreign_key(op.f('test_results_ibfk_3'), 'test_results', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'status_history', type_='foreignkey')
    op.create_foreign_key(op.f('status_history_ibfk_1'), 'status_history', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'hook_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('hook_sessions_ibfk_4'), 'hook_sessions', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'failure_records', type_='foreignkey')
    op.create_foreign_key(op.f('failure_records_ibfk_2'), 'failure_records', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_ibfk_1'), 'comments', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_ibfk_3'), 'alerts', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###
