"""add hook_sessions table

Revision ID: beb4ba35f9b0
Revises: 31ae763f567d
Create Date: 2026-04-09 09:19:31.208454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb4ba35f9b0'
down_revision: Union[str, None] = '31ae763f567d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hook_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('transcript_path', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('sprint_id', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('token_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'error', name='hooksessionstatus'), nullable=False),
    sa.Column('session_type', sa.Enum('main', 'teammate', 'subagent', name='hooksessiontype'), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('hook_event', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hook_sessions_agent_id'), 'hook_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_hook_sessions_project_id'), 'hook_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_hook_sessions_session_id'), 'hook_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_hook_sessions_sprint_id'), 'hook_sessions', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_hook_sessions_ticket_id'), 'hook_sessions', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hook_sessions_ticket_id'), table_name='hook_sessions')
    op.drop_index(op.f('ix_hook_sessions_sprint_id'), table_name='hook_sessions')
    op.drop_index(op.f('ix_hook_sessions_session_id'), table_name='hook_sessions')
    op.drop_index(op.f('ix_hook_sessions_project_id'), table_name='hook_sessions')
    op.drop_index(op.f('ix_hook_sessions_agent_id'), table_name='hook_sessions')
    op.drop_table('hook_sessions')
    # ### end Alembic commands ###
