"""add sprint_id and ticket_id to test_results

Revision ID: c59eb682137a
Revises: d838d1a49a2e
Create Date: 2026-03-27 13:25:39.371229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59eb682137a'
down_revision: Union[str, None] = 'd838d1a49a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('sprint_id', sa.BigInteger(), nullable=True))
    op.add_column('test_results', sa.Column('ticket_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_test_results_sprint_id'), 'test_results', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_test_results_ticket_id'), 'test_results', ['ticket_id'], unique=False)
    op.create_foreign_key(None, 'test_results', 'sprints', ['sprint_id'], ['id'])
    op.create_foreign_key(None, 'test_results', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.drop_index(op.f('ix_test_results_ticket_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_sprint_id'), table_name='test_results')
    op.drop_column('test_results', 'ticket_id')
    op.drop_column('test_results', 'sprint_id')
    # ### end Alembic commands ###
