"""add repo_path to projects

Revision ID: d838d1a49a2e
Revises: 7c2db5e29c01
Create Date: 2026-03-27 12:34:12.171152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd838d1a49a2e'
down_revision: Union[str, None] = '7c2db5e29c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('repo_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'repo_path')
    # ### end Alembic commands ###
