# Path: alembic/versions/dwb004a1b2c3_add_force_coding_standards_md_gate.py
# File: dwb004a1b2c3_add_force_coding_standards_md_gate.py
# Created: 2026-08-10
# Purpose: Add projects.force_coding_standards_md sprint-gate toggle (DWB-004)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb481a1b2c3
# Data Out: projects.force_coding_standards_md column (bool, default off)
# Last Modified: 2026-08-10

"""add force_coding_standards_md gate (DWB-004)

Revision ID: dwb004a1b2c3
Revises: dwb481a1b2c3
Create Date: 2026-08-10 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted for new tables.

Fourth doc gate alongside force_initial_md / force_architecture_md /
force_handoff_md: when on, sprint close requires CODING_STANDARDS.md at the
project repo root. Defaults off (opt-in, matching initial/architecture; only
handoff is opt-out).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb004a1b2c3"
down_revision: Union[str, None] = "dwb481a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "projects",
        sa.Column(
            "force_coding_standards_md",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )


def downgrade() -> None:
    op.drop_column("projects", "force_coding_standards_md")
