# Path: alembic/versions/dwb016a1b2c3_add_audit_score_enums.py
# File: dwb016a1b2c3_add_audit_score_enums.py
# Created: 2026-08-11 (DWB-016)
# Purpose: Extend the score_event ENUM columns so a standards-audit scorecard can
#          be applied to the ledger: add source='audit' and trigger_type values
#          'audit_grant' / 'audit_demerit'.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb014a1b2c3
# Data Out: widened score_event.source and score_event.trigger_type ENUMs
# Last Modified: 2026-08-11 (DWB-016)

"""add audit score enums (DWB-016)

Revision ID: dwb016a1b2c3
Revises: dwb014a1b2c3
Create Date: 2026-08-11 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate is not
trusted (and does not reliably emit ENUM widenings).

DWB-016 applies an audit scorecard to the DWB-424 ledger. score_event needs two
new enum values on `source` ('audit') and two on `trigger_type` ('audit_grant',
'audit_demerit'). MySQL stores ENUMs inline, so widening is a MODIFY COLUMN with
the full value list (existing + new). Additive only - no data rewrite.

Downgrade narrows the ENUMs back to their pre-DWB-016 sets. That MODIFY fails if
any row already uses an audit value (MySQL truncates on narrowing); acceptable
for a downgrade - reverse-apply the audits first if you must roll back.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "dwb016a1b2c3"
down_revision: Union[str, None] = "dwb014a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Full value lists AFTER this migration (order matches the Python enums).
_SOURCE_NEW = "'auto','human','peer','audit'"
_TRIGGER_NEW = (
    "'ticket_closed','rework','test_failure','stale','zero_token_close',"
    "'gate_miss','forgot','carrot','stick','peer_grant','peer_demerit',"
    "'audit_grant','audit_demerit'"
)

# Pre-DWB-016 value lists (for downgrade).
_SOURCE_OLD = "'auto','human','peer'"
_TRIGGER_OLD = (
    "'ticket_closed','rework','test_failure','stale','zero_token_close',"
    "'gate_miss','forgot','carrot','stick','peer_grant','peer_demerit'"
)


def upgrade() -> None:
    op.execute(
        f"ALTER TABLE score_event MODIFY COLUMN source ENUM({_SOURCE_NEW}) NOT NULL"
    )
    op.execute(
        f"ALTER TABLE score_event MODIFY COLUMN trigger_type "
        f"ENUM({_TRIGGER_NEW}) NOT NULL"
    )


def downgrade() -> None:
    op.execute(
        f"ALTER TABLE score_event MODIFY COLUMN trigger_type "
        f"ENUM({_TRIGGER_OLD}) NOT NULL"
    )
    op.execute(
        f"ALTER TABLE score_event MODIFY COLUMN source ENUM({_SOURCE_OLD}) NOT NULL"
    )
