# Path: alembic/versions/dwb017a1b2c3_add_force_standards_audit_gate.py
# File: dwb017a1b2c3_add_force_standards_audit_gate.py
# Created: 2026-08-11 (DWB-017)
# Purpose: Add projects.force_standards_audit sprint-gate toggle (DWB-017) - when
#          on, sprint close requires a PASSING standards audit recorded since the
#          sprint started. Complements force_coding_standards_md.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb016a1b2c3
# Data Out: projects.force_standards_audit column (bool, default off)
# Last Modified: 2026-08-11 (DWB-017)

"""add force_standards_audit gate (DWB-017)

Revision ID: dwb017a1b2c3
Revises: dwb016a1b2c3
Create Date: 2026-08-11 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted.

Mirrors the force_test_run gate: when on, sprint close is blocked unless a
standards_audit with verdict=pass exists for the project dated at/after the
sprint start. Defaults off (opt-in). This COMPLEMENTS force_coding_standards_md
(the file gate asserts the standards doc exists; the audit gate asserts the code
actually conforms) - both stay.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb017a1b2c3"
down_revision: Union[str, None] = "dwb016a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "projects",
        sa.Column(
            "force_standards_audit",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )


def downgrade() -> None:
    op.drop_column("projects", "force_standards_audit")
