# Path: alembic/versions/dwb014a1b2c3_add_standards_audit_table.py
# File: dwb014a1b2c3_add_standards_audit_table.py
# Created: 2026-08-11 (DWB-014)
# Purpose: Create the standards_audit table - storage for recorded PR standards
#          audits (verdict + violations JSON + per-agent scorecard JSON + raw
#          diff/output as MEDIUMTEXT).
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb004a1b2c3
# Data Out: standards_audit table
# Last Modified: 2026-08-11 (DWB-014)

"""add standards_audit table (DWB-014)

Revision ID: dwb014a1b2c3
Revises: dwb004a1b2c3
Create Date: 2026-08-11 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate is not
trusted for new tables (spurious drop_index ops on error_logs and unreliable
ENUM / MEDIUMTEXT emission).

Storage for a PR standards audit. violations and scorecard are JSON columns (no
child audit_violation table - an audit is read whole, not queried per-violation;
see the model header). `details` is MEDIUMTEXT so a large raw diff / auditor
output does not overflow TEXT's 64KB cap (mirrors test_result.details, DWB-308).
verdict is ENUM('pass','reject'). Recording an audit does not apply its
scorecard - that is DWB-016.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


revision: str = "dwb014a1b2c3"
down_revision: Union[str, None] = "dwb004a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "standards_audit",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("sprint_id", sa.BigInteger(), nullable=True),
        sa.Column("ticket_id", sa.BigInteger(), nullable=True),
        sa.Column("pr_ref", sa.String(length=255), nullable=False),
        sa.Column("diff_range", sa.String(length=255), nullable=True),
        sa.Column(
            "verdict",
            sa.Enum("pass", "reject", name="auditverdict"),
            nullable=False,
        ),
        sa.Column("violations", sa.JSON(), nullable=True),
        sa.Column("scorecard", sa.JSON(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "details",
            sa.Text().with_variant(mysql.MEDIUMTEXT(), "mysql"),
            nullable=True,
        ),
        sa.Column(
            "run_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "triggered_by",
            sa.String(length=100),
            server_default="manual",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.ForeignKeyConstraint(["sprint_id"], ["sprints.id"]),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["tickets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_standards_audit_project_id", "standards_audit", ["project_id"]
    )
    op.create_index(
        "ix_standards_audit_sprint_id", "standards_audit", ["sprint_id"]
    )
    op.create_index(
        "ix_standards_audit_ticket_id", "standards_audit", ["ticket_id"]
    )


def downgrade() -> None:
    op.drop_index("ix_standards_audit_ticket_id", table_name="standards_audit")
    op.drop_index("ix_standards_audit_sprint_id", table_name="standards_audit")
    op.drop_index("ix_standards_audit_project_id", table_name="standards_audit")
    op.drop_table("standards_audit")
