# Path: alembic/versions/dwb381b4d8f0a2_add_slash_to_dwb_session_method_enums.py
# File: dwb381b4d8f0a2_add_slash_to_dwb_session_method_enums.py
# Created: 2026-06-11
# Purpose: Add 'slash' value to dwb_sessions.open_method and close_method ENUMs (DWB-381)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: N/A (DDL migration)
# Data Out: N/A (DDL migration)
# Last Modified: 2026-06-11

"""add slash to dwb session method enums (DWB-381)

Revision ID: dwb381b4d8f0a2
Revises: dwb371b2e8f5a
Create Date: 2026-06-11 12:30:00.000000

Hand-written, not autogenerated. MySQL ENUM extensions require an explicit
MODIFY COLUMN listing every member (existing + new); Alembic autogenerate
misses enum changes on MySQL (per project rules + prior DWB-335 / DWB-336
session-arc gotchas).

DWB-381 ships a `/dwb-open` and `/dwb-close` slash-command escape hatch. The
slash command curls /api/sessions/open / /api/sessions/{id}/close with
open_method=slash / close_method=slash, so the column ENUM has to learn the
new value before the API can persist a row stamped with it.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "dwb381b4d8f0a2"
down_revision: Union[str, None] = "dwb371b2e8f5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE dwb_sessions MODIFY COLUMN open_method "
        "ENUM('regex','ai_confident','ai_asked','slash') NOT NULL"
    )
    op.execute(
        "ALTER TABLE dwb_sessions MODIFY COLUMN close_method "
        "ENUM('regex','ai_confident','ai_asked','idle_timeout','slash') NULL"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE dwb_sessions MODIFY COLUMN open_method "
        "ENUM('regex','ai_confident','ai_asked') NOT NULL"
    )
    op.execute(
        "ALTER TABLE dwb_sessions MODIFY COLUMN close_method "
        "ENUM('regex','ai_confident','ai_asked','idle_timeout') NULL"
    )
