# Path: alembic/versions/dwb331a7c8f4d_single_active_epic_sprint.py
# File: dwb331a7c8f4d_single_active_epic_sprint.py
# Created: 2026-06-09
# Purpose: Add generated columns + UNIQUE indexes for single-in_progress-epic and single-active-sprint per project (DWB-331)
# Caller: alembic upgrade head
# Callees: alembic.op, epics + sprints tables
# Data In: current schema at dwb335a7b3c91
# Data Out: epics.is_in_progress generated column + uq_epics_one_in_progress_per_project index; sprints.is_active generated column + uq_sprints_one_active_per_project index
# Last Modified: 2026-06-09

"""single-in_progress-epic and single-active-sprint per project (DWB-331)

Revision ID: dwb331a7c8f4d
Revises: dwb335a7b3c91
Create Date: 2026-06-09 15:50:00.000000

Hand-written, not autogenerated — Alembic's MySQL diff misses generated
columns (same gotcha as DWB-335).

Adds two STORED generated columns plus a UNIQUE composite index on each:

  epics.is_in_progress  = CASE WHEN status = 'in_progress' THEN 1 ELSE NULL END
    UNIQUE INDEX uq_epics_one_in_progress_per_project (project_id, is_in_progress)

  sprints.is_active     = CASE WHEN status = 'active' THEN 1 ELSE NULL END
    UNIQUE INDEX uq_sprints_one_active_per_project (project_id, is_active)

MySQL treats NULL as distinct in UNIQUE, so closed rows (is_* = NULL)
never collide; only one in_progress epic and one active sprint per
project_id can hold the marker = 1.

The ticket spec said DWB data is clean. In practice the working DB also
hosts other projects (e.g. RVP / Portal) where stale active sprints
linger. The migration auto-resolves such drift before applying the
constraint: for every project with multiple in_progress epics (or
multiple active sprints), keep the highest-id row (newest by insertion)
and close the rest to completed. The change is logged so it shows up
in `alembic upgrade` output.

Same deterministic policy DWB-315 used for the colliding agent-name
case: pick a tiebreaker that matches user intent in the common case,
write it down, log what changed.
"""

import logging
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb331a7c8f4d"
down_revision: Union[str, None] = "dwb335a7b3c91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


logger = logging.getLogger("alembic.runtime.migration")


def _resolve_dupes(
    bind,
    table: str,
    status_col: str,
    status_value: str,
    closed_value: str,
) -> None:
    """Auto-close stale duplicates so the new UNIQUE constraint applies
    cleanly. Policy: keep the highest-id row per project_id (newest by
    insertion order), set everything else to `closed_value`. Logs what
    changed."""
    dupe_rows = bind.execute(
        sa.text(
            f"SELECT project_id, COUNT(*) AS n FROM {table} "
            f"WHERE {status_col} = :v GROUP BY project_id HAVING COUNT(*) > 1"
        ),
        {"v": status_value},
    ).fetchall()
    if not dupe_rows:
        return

    for dupe in dupe_rows:
        project_id = dupe.project_id
        rows = bind.execute(
            sa.text(
                f"SELECT id FROM {table} "
                f"WHERE project_id = :pid AND {status_col} = :v "
                f"ORDER BY id DESC"
            ),
            {"pid": project_id, "v": status_value},
        ).fetchall()
        keep_id = rows[0].id
        close_ids = [r.id for r in rows[1:]]
        bind.execute(
            sa.text(
                f"UPDATE {table} SET {status_col} = :closed "
                f"WHERE id IN :ids"
            ).bindparams(sa.bindparam("ids", expanding=True)),
            {"closed": closed_value, "ids": close_ids},
        )
        logger.info(
            "DWB-331 migration: %s project_id=%s — kept id=%s as %s, "
            "closed id(s)=%s to %s",
            table,
            project_id,
            keep_id,
            status_value,
            close_ids,
            closed_value,
        )


def upgrade() -> None:
    bind = op.get_bind()

    # Pre-flight: normalise any drift so the new UNIQUE index can apply.
    # Deterministic policy — keep the highest-id row, close the rest.
    _resolve_dupes(bind, "epics", "status", "in_progress", "completed")
    _resolve_dupes(bind, "sprints", "status", "active", "completed")

    # epics.is_in_progress + UNIQUE(project_id, is_in_progress)
    op.add_column(
        "epics",
        sa.Column(
            "is_in_progress",
            sa.SmallInteger(),
            sa.Computed(
                "(CASE WHEN status = 'in_progress' THEN 1 ELSE NULL END)",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "uq_epics_one_in_progress_per_project",
        "epics",
        ["project_id", "is_in_progress"],
        unique=True,
    )

    # sprints.is_active + UNIQUE(project_id, is_active)
    op.add_column(
        "sprints",
        sa.Column(
            "is_active",
            sa.SmallInteger(),
            sa.Computed(
                "(CASE WHEN status = 'active' THEN 1 ELSE NULL END)",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "uq_sprints_one_active_per_project",
        "sprints",
        ["project_id", "is_active"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index(
        "uq_sprints_one_active_per_project", table_name="sprints"
    )
    op.drop_column("sprints", "is_active")

    op.drop_index(
        "uq_epics_one_in_progress_per_project", table_name="epics"
    )
    op.drop_column("epics", "is_in_progress")
