# Path: alembic/versions/dwb382c5e9f0b3_add_ai_classifier_to_dwb_session_enums.py
# File: dwb382c5e9f0b3_add_ai_classifier_to_dwb_session_enums.py
# Created: 2026-06-11
# Purpose: Add 'ai_classifier' value to dwb_sessions.open_method and close_method ENUMs (DWB-382 Layer-2 Haiku fallback)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: N/A (DDL migration)
# Data Out: N/A (DDL migration)
# Last Modified: 2026-06-11

"""add ai_classifier to dwb session method enums (DWB-382)

Revision ID: dwb382c5e9f0b3
Revises: dwb381b4d8f0a2
Create Date: 2026-06-11 14:00:00.000000

Hand-written, not autogenerated. MySQL ENUM extensions require an explicit
MODIFY COLUMN listing every member (existing + new); Alembic autogenerate
misses enum changes on MySQL (per project rules + prior DWB-335 / DWB-336
session-arc gotchas; same pattern as DWB-381 dwb381b4d8f0a2).

DWB-382 ships an async Haiku classifier as a Layer-2 backstop. Triggered
only when the UserPromptSubmit hook's match_open AND match_close both miss
on the catalogued phrase regex, the classifier fire-and-forget hits
Anthropic Haiku to infer intent. On high-confidence open/close it opens or
closes a DWB session stamped with the new `ai_classifier` method value.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "dwb382c5e9f0b3"
down_revision: Union[str, None] = "dwb381b4d8f0a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE dwb_sessions MODIFY COLUMN open_method "
        "ENUM('regex','ai_confident','ai_asked','slash','ai_classifier') "
        "NOT NULL"
    )
    op.execute(
        "ALTER TABLE dwb_sessions MODIFY COLUMN close_method "
        "ENUM('regex','ai_confident','ai_asked','idle_timeout','slash',"
        "'ai_classifier') NULL"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE dwb_sessions MODIFY COLUMN open_method "
        "ENUM('regex','ai_confident','ai_asked','slash') NOT NULL"
    )
    op.execute(
        "ALTER TABLE dwb_sessions MODIFY COLUMN close_method "
        "ENUM('regex','ai_confident','ai_asked','idle_timeout','slash') NULL"
    )
