# Path: alembic/versions/dwb342f8b9c10_jira_snapshot_and_sync_state.py
# File: dwb342f8b9c10_jira_snapshot_and_sync_state.py
# Created: 2026-06-10
# Purpose: Create jira_ticket_snapshots table + add Jira sync-state columns to projects (DWB-342)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema (projects, tickets)
# Data Out: jira_ticket_snapshots table; projects.last_jira_sync_at + _status + _counts
# Last Modified: 2026-06-10

"""DWB-342: jira_ticket_snapshots table + project sync-state columns

Revision ID: dwb342f8b9c10
Revises: dwb351d4f7a93
Create Date: 2026-06-10 14:10:00.000000

Hand-written, not autogenerated (per the project's standing rule on
MySQL enum / FK edges).

Two changes:

  1. New table ``jira_ticket_snapshots`` - one row per linked DWB ticket
     holding the cached Jira-side fields the DWB-342 list endpoint serves.
     Sibling table (not extra columns on tickets) so non-Jira projects
     don't pay the storage cost, and the cache can be dropped + rebuilt
     without touching canonical ticket rows. UNIQUE on ticket_id enforces
     the one-to-one mapping; ON DELETE CASCADE so deleting a ticket also
     drops its snapshot.

  2. Three new columns on ``projects`` for the manual-sync UX:
     - last_jira_sync_at        DATETIME NULL
     - last_jira_sync_status    ENUM('idle','running','done','error')
                                NOT NULL DEFAULT 'idle'
     - last_jira_sync_counts    JSON NULL (e.g. {added:N, updated:N,
                                unchanged:N, missing:N, errors:[]})

Backfill: none. New projects default to idle. Pre-existing projects
will show last_jira_sync_at=NULL until the first manual sync runs.

Downgrade is symmetric: drops the columns + drops the table.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb342f8b9c10"
down_revision: Union[str, None] = "dwb351d4f7a93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "jira_ticket_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.BigInteger(), nullable=False),
        sa.Column("jira_issue_key", sa.String(length=50), nullable=False),
        sa.Column("jira_status", sa.String(length=50), nullable=True),
        sa.Column("jira_sprint_name", sa.String(length=255), nullable=True),
        sa.Column("jira_assignee", sa.String(length=255), nullable=True),
        sa.Column("jira_reporter", sa.String(length=255), nullable=True),
        sa.Column("jira_title", sa.String(length=500), nullable=True),
        sa.Column("jira_description", sa.Text(), nullable=True),
        sa.Column("jira_created_at", sa.DateTime(), nullable=True),
        sa.Column("jira_updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["tickets.id"], ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jira_ticket_snapshots_ticket_id"),
        "jira_ticket_snapshots",
        ["ticket_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_jira_ticket_snapshots_jira_issue_key"),
        "jira_ticket_snapshots",
        ["jira_issue_key"],
        unique=False,
    )

    op.add_column(
        "projects",
        sa.Column("last_jira_sync_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column(
            "last_jira_sync_status",
            sa.Enum(
                "idle", "running", "done", "error",
                name="jirasyncstatus",
            ),
            nullable=False,
            server_default="idle",
        ),
    )
    op.add_column(
        "projects",
        sa.Column("last_jira_sync_counts", sa.JSON(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("projects", "last_jira_sync_counts")
    op.drop_column("projects", "last_jira_sync_status")
    op.drop_column("projects", "last_jira_sync_at")

    op.drop_index(
        op.f("ix_jira_ticket_snapshots_jira_issue_key"),
        table_name="jira_ticket_snapshots",
    )
    op.drop_index(
        op.f("ix_jira_ticket_snapshots_ticket_id"),
        table_name="jira_ticket_snapshots",
    )
    op.drop_table("jira_ticket_snapshots")
