# Path: alembic/versions/dwb346b8e2c91_add_headline_to_dwb_sessions.py
# File: dwb346b8e2c91_add_headline_to_dwb_sessions.py
# Created: 2026-06-10
# Purpose: Add dwb_sessions.headline (VARCHAR(80) NULL) for user-facing session summary on close (DWB-346)
# Caller: alembic upgrade head
# Callees: alembic.op, dwb_sessions table
# Data In: existing schema (dwb_sessions table from dwb335a7b3c91)
# Data Out: dwb_sessions.headline column
# Last Modified: 2026-06-10

"""add headline column to dwb_sessions (DWB-346)

Revision ID: dwb346b8e2c91
Revises: dwb331a7c8f4d
Create Date: 2026-06-10 12:15:00.000000

Hand-written, not autogenerated. Alembic's MySQL diff has bitten this
codebase repeatedly on enum/generated-column changes, so all DWB migrations
that touch dwb_sessions are written by hand (per the DWB-335 migration's
own header note and the worker playbook's migration rule).

Schema change:

  ALTER TABLE dwb_sessions
    ADD COLUMN headline VARCHAR(80) NULL;

Nullable, no default. Set by POST /api/sessions/{id}/close when the caller
supplies a `headline` body field; otherwise stays NULL. 80-char cap so the
dashboard sessions list row stays one line.

Backfill: none. Pre-existing closed rows stay headline=NULL; the list
endpoint serves NULL to the dashboard which falls back to the auto-derived
`ticket_summary`.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb346b8e2c91"
down_revision: Union[str, None] = "dwb331a7c8f4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "dwb_sessions",
        sa.Column("headline", sa.String(length=80), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("dwb_sessions", "headline")
