# Path: alembic/versions/dwb335a7b3c91_add_dwb_sessions_table.py
# File: dwb335a7b3c91_add_dwb_sessions_table.py
# Created: 2026-06-09
# Purpose: Create dwb_sessions table + single-active constraint, add FK on hook_sessions (DWB-335)
# Caller: alembic upgrade head
# Callees: alembic.op, dwb_sessions table, hook_sessions table
# Data In: existing schema (hook_sessions at beb4ba35f9b0+)
# Data Out: dwb_sessions table, hook_sessions.dwb_session_id column
# Last Modified: 2026-06-09

"""add dwb_sessions table and hook_sessions FK (DWB-335)

Revision ID: dwb335a7b3c91
Revises: dwb328e7a91b
Create Date: 2026-06-09 15:10:00.000000

Hand-written, not autogenerated — Alembic's MySQL diff misses generated
columns and enum changes (per project rules / prior session gotchas).

Schema:
  dwb_sessions
    id, project_id (FK projects.id, indexed)
    opened_at NOT NULL, closed_at NULL
    open_phrase TEXT NULL, close_phrase TEXT NULL
    open_method ENUM(regex, ai_confident, ai_asked) NOT NULL
    close_method ENUM(regex, ai_confident, ai_asked, idle_timeout) NULL
    close_reason ENUM(explicit, idle, manual) NULL
    total_tokens INT NOT NULL DEFAULT 0
    total_time_seconds INT NOT NULL DEFAULT 0
    is_open SMALLINT GENERATED ALWAYS AS (CASE WHEN closed_at IS NULL THEN 1
        ELSE NULL END) STORED
    created_at, updated_at

Single-active constraint:
  UNIQUE INDEX (project_id, is_open). MySQL treats NULL as distinct in
  UNIQUE, so closed rows (is_open=NULL) never collide; only one open row
  per project_id can hold is_open=1.

  Generated-column-plus-UNIQUE was chosen over BEFORE INSERT/UPDATE
  triggers because:
    - declarative; lives with the table schema, not in PL/SQL on the side
    - SQLAlchemy renders it from the model (`Computed(...)` + `Index(...)`)
      so `Base.metadata.create_all` in tests gets the same constraint
    - no procedural code to maintain or test in isolation
    - DWB-331 will use the same pattern on sprints / epics (single active
      per project, single in_progress per project)

hook_sessions FK:
  Adds dwb_session_id (BIGINT NULL, indexed, FK -> dwb_sessions.id).
  Historical rows stay NULL — no backfill. Future hook ingestion sets it
  when an open DWB session exists for the project at hook receipt time.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb335a7b3c91"
down_revision: Union[str, None] = "dwb328e7a91b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "dwb_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("open_phrase", sa.Text(), nullable=True),
        sa.Column("close_phrase", sa.Text(), nullable=True),
        sa.Column(
            "open_method",
            sa.Enum(
                "regex",
                "ai_confident",
                "ai_asked",
                name="dwbopenmethod",
            ),
            nullable=False,
        ),
        sa.Column(
            "close_method",
            sa.Enum(
                "regex",
                "ai_confident",
                "ai_asked",
                "idle_timeout",
                name="dwbclosemethod",
            ),
            nullable=True,
        ),
        sa.Column(
            "close_reason",
            sa.Enum(
                "explicit",
                "idle",
                "manual",
                name="dwbclosereason",
            ),
            nullable=True,
        ),
        sa.Column(
            "total_tokens",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "total_time_seconds",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "is_open",
            sa.SmallInteger(),
            sa.Computed(
                "(CASE WHEN closed_at IS NULL THEN 1 ELSE NULL END)",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dwb_sessions_project_id"),
        "dwb_sessions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "uq_dwb_sessions_one_open_per_project",
        "dwb_sessions",
        ["project_id", "is_open"],
        unique=True,
    )

    # hook_sessions.dwb_session_id — NULL allowed, indexed, FK to dwb_sessions.
    # No backfill: historical rows predate DWB sessions and must remain valid.
    op.add_column(
        "hook_sessions",
        sa.Column("dwb_session_id", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        op.f("ix_hook_sessions_dwb_session_id"),
        "hook_sessions",
        ["dwb_session_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_hook_sessions_dwb_session_id",
        "hook_sessions",
        "dwb_sessions",
        ["dwb_session_id"],
        ["id"],
    )


def downgrade() -> None:
    # Look up the actual FK constraint name on hook_sessions.dwb_session_id.
    # The migration's upgrade names it `fk_hook_sessions_dwb_session_id`, but
    # a database initialized via SQLAlchemy `Base.metadata.create_all` (e.g.
    # the test DB) gets an autogenerated name. Resolve at runtime so down is
    # robust across both origins.
    bind = op.get_bind()
    row = bind.execute(
        sa.text(
            "SELECT CONSTRAINT_NAME FROM "
            "information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() "
            "AND TABLE_NAME = 'hook_sessions' "
            "AND COLUMN_NAME = 'dwb_session_id' "
            "AND REFERENCED_TABLE_NAME = 'dwb_sessions'"
        )
    ).fetchone()
    if row is not None:
        op.drop_constraint(row.CONSTRAINT_NAME, "hook_sessions", type_="foreignkey")
    op.drop_index(
        op.f("ix_hook_sessions_dwb_session_id"), table_name="hook_sessions"
    )
    op.drop_column("hook_sessions", "dwb_session_id")

    # drop_table cleans up the FK + child indexes; explicit index drops are
    # unnecessary and MySQL refuses to drop ix_dwb_sessions_project_id while
    # the FK to projects.id still needs it.
    op.drop_table("dwb_sessions")
    # Enum types are dropped automatically with the table on MySQL (they're
    # column-level, not standalone types like Postgres). No explicit drop.
