# Path: alembic/versions/dwb454a1b2c3_subtask_type_and_parent_ticket_id.py
# File: dwb454a1b2c3_subtask_type_and_parent_ticket_id.py
# Created: 2026-06-24
# Purpose: Add 'subtask' to the ticket_type enum + self-referential tickets.parent_ticket_id (DWB-454)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb446a1b2c3
# Data Out: widened ticket_type enum + tickets.parent_ticket_id column/index/FK
# Last Modified: 2026-06-24

"""subtask type + parent_ticket_id self-ref (DWB-454)

Revision ID: dwb454a1b2c3
Revises: dwb446a1b2c3
Create Date: 2026-06-24 13:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted.

Native sub-task support (epic 36). Two schema changes:
  1. Widen the tickets.ticket_type MySQL ENUM to add 'subtask'. MySQL stores
     the enum inline on the column, so this is a MODIFY COLUMN that preserves
     every existing value (task/bug/story rows are untouched).
  2. Add tickets.parent_ticket_id: a nullable self-referential FK -> tickets.id,
     indexed, ON DELETE SET NULL. Only subtask-type tickets set it (enforced at
     the service/router layer in DWB-455); existing rows stay NULL.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb454a1b2c3"
down_revision: Union[str, None] = "dwb446a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Widen the enum. MySQL keeps existing values during a MODIFY that only
    #    adds members, so task/bug/story rows are preserved.
    op.execute(
        "ALTER TABLE tickets MODIFY ticket_type "
        "ENUM('task', 'bug', 'story', 'subtask') NOT NULL"
    )

    # 2. Self-referential parent link.
    op.add_column(
        "tickets",
        sa.Column("parent_ticket_id", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        "ix_tickets_parent_ticket_id",
        "tickets",
        ["parent_ticket_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_tickets_parent_ticket_id",
        "tickets",
        "tickets",
        ["parent_ticket_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # Reverse order: drop the FK + index + column first, then narrow the enum.
    op.drop_constraint("fk_tickets_parent_ticket_id", "tickets", type_="foreignkey")
    op.drop_index("ix_tickets_parent_ticket_id", table_name="tickets")
    op.drop_column("tickets", "parent_ticket_id")
    # Narrow the enum back. Any rows still set to 'subtask' would block this;
    # callers must reclassify those before downgrading.
    op.execute(
        "ALTER TABLE tickets MODIFY ticket_type "
        "ENUM('task', 'bug', 'story') NOT NULL"
    )
