# Path: alembic/versions/dwb462a1b2c3_alert_category.py
# File: dwb462a1b2c3_alert_category.py
# Created: 2026-06-24
# Purpose: Add alerts.category enum (comms/scoring/actionable) + backfill existing rows by inference (DWB-462)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb454a1b2c3
# Data Out: alerts.category column (NOT NULL, default actionable) with existing rows classified
# Last Modified: 2026-06-24

"""alerts.category taxonomy + backfill (DWB-462)

Revision ID: dwb462a1b2c3
Revises: dwb454a1b2c3
Create Date: 2026-06-24 14:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted.

Epic 37 "Alerts vs Actions". Adds a category enum to alerts so the dashboard
can separate true alerts (comms / scoring / actionable) from activity-feed
actions (demoted in DWB-463). The column is added with server_default
'actionable' so every existing row gets a valid value immediately; the backfill
then reclassifies comms + scoring rows by title inference (everything else
stays actionable, which is the correct bucket for rework / stale / gate /
test-run / sprint-close rows).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb462a1b2c3"
down_revision: Union[str, None] = "dwb454a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "alerts",
        sa.Column(
            "category",
            sa.Enum("comms", "scoring", "actionable", name="alertcategory"),
            nullable=False,
            server_default="actionable",
        ),
    )
    op.create_index("ix_alerts_category", "alerts", ["category"], unique=False)

    # Backfill by inference. Existing rows default to 'actionable' (the column
    # server_default), so we only need to flip the comms + scoring rows.
    #
    # comms: TL-channel pings (tl_channel._ping).
    op.execute(
        "UPDATE alerts SET category = 'comms' "
        "WHERE title LIKE 'TL message from%' "
        "OR title LIKE '%broadcast to all team-leads%'"
    )
    # scoring: reputation carrots/sticks (scoring.broadcast_score_change). The
    # signed delta in the title ('+N' / '-N' after 'received ') is a robust
    # discriminator that won't catch unrelated 'received' prose.
    op.execute(
        "UPDATE alerts SET category = 'scoring' "
        "WHERE title LIKE 'You received +%' "
        "OR title LIKE 'You received -%' "
        "OR title LIKE '%received +%from%' "
        "OR title LIKE '%received -%from%'"
    )


def downgrade() -> None:
    op.drop_index("ix_alerts_category", table_name="alerts")
    op.drop_column("alerts", "category")
