# Path: alembic/versions/dwb436a1b2c3_add_tl_channel_tables.py
# File: dwb436a1b2c3_add_tl_channel_tables.py
# Created: 2026-06-23
# Purpose: Create the cross-project team-lead channel tables tl_messages + tl_message_reads (DWB-436)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb426a1b2c3
# Data Out: tl_messages + tl_message_reads tables
# Last Modified: 2026-06-23

"""add tl_messages + tl_message_reads (DWB-436)

Revision ID: dwb436a1b2c3
Revises: dwb426a1b2c3
Create Date: 2026-06-23 12:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted.

The "Archie Channel": cross-project team-lead messaging. NOT project-scoped -
``from_project_id`` only records the sender's home project; the channel spans
projects. ``to_agent_id`` NULL = broadcast. tl_message_reads is a per-(message,
agent) read receipt with a composite PK so a re-read is idempotent; its
message_id FK is ON DELETE CASCADE so deleting a message clears its receipts.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb436a1b2c3"
down_revision: Union[str, None] = "dwb426a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "tl_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("from_agent_id", sa.BigInteger(), nullable=False),
        sa.Column("to_agent_id", sa.BigInteger(), nullable=True),
        sa.Column("from_project_id", sa.BigInteger(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["from_agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["to_agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["from_project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tl_messages_from_agent_id"),
        "tl_messages",
        ["from_agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tl_messages_to_agent_id"),
        "tl_messages",
        ["to_agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tl_messages_from_project_id"),
        "tl_messages",
        ["from_project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tl_messages_created_at"),
        "tl_messages",
        ["created_at"],
        unique=False,
    )

    op.create_table(
        "tl_message_reads",
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("agent_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "read_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["tl_messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.PrimaryKeyConstraint("message_id", "agent_id"),
    )


def downgrade() -> None:
    # drop_table removes the table's own indexes and FK constraints; dropping
    # the indexes explicitly first fails on MySQL because they back the FKs.
    op.drop_table("tl_message_reads")
    op.drop_table("tl_messages")
