# Path: alembic/versions/dwb446a1b2c3_add_inter_agent_messages_table.py
# File: dwb446a1b2c3_add_inter_agent_messages_table.py
# Created: 2026-06-24
# Purpose: Create inter_agent_messages table + projects.capture_agent_comms flag (DWB-446)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb436a1b2c3
# Data Out: inter_agent_messages table + projects.capture_agent_comms column
# Last Modified: 2026-06-24

"""add inter_agent_messages table + projects.capture_agent_comms (DWB-446)

Revision ID: dwb446a1b2c3
Revises: dwb436a1b2c3
Create Date: 2026-06-24 12:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted for new tables.

Epic 35 "Inter-Agent Comms Capture & Log": one row per agent-to-agent message
captured from the SendMessage hook (DWB-447). The table is project-scoped
(project_id NOT NULL drives the list/purge/delete queries). dwb_session_id is
display-only - it is NOT used for purge; the age-based sweep (DWB-449) keys off
created_at alone, so messages survive session close. from_agent_id/to_agent_id
are best-effort resolutions and nullable; the *_name varchars always carry the
human-readable label even when the FK can't resolve. capture_agent_comms on
projects gates capture per-project (default TRUE).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb446a1b2c3"
down_revision: Union[str, None] = "dwb436a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "projects",
        sa.Column(
            "capture_agent_comms",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.create_table(
        "inter_agent_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("dwb_session_id", sa.BigInteger(), nullable=True),
        sa.Column("from_agent_id", sa.BigInteger(), nullable=True),
        sa.Column("from_agent_name", sa.String(length=255), nullable=True),
        sa.Column("to_agent_name", sa.String(length=255), nullable=True),
        sa.Column("to_agent_id", sa.BigInteger(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("summary", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.ForeignKeyConstraint(["dwb_session_id"], ["dwb_sessions.id"]),
        sa.ForeignKeyConstraint(["from_agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["to_agent_id"], ["agents.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inter_agent_messages_project_created",
        "inter_agent_messages",
        ["project_id", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    # drop_table removes the table's own indexes and FK constraints on MySQL.
    op.drop_table("inter_agent_messages")
    op.drop_column("projects", "capture_agent_comms")
