# Path: alembic/versions/dwb426a1b2c3_alert_recipient_agent.py
# File: dwb426a1b2c3_alert_recipient_agent.py
# Created: 2026-06-22
# Purpose: Add alerts.recipient_agent_id for per-agent broadcast notifications (DWB-426)
# Caller: alembic upgrade head
# Callees: alembic.op, alerts table
# Data In: existing schema at dwb424a1b2c3
# Data Out: alerts.recipient_agent_id column + index + FK
# Last Modified: 2026-06-22

"""add alerts.recipient_agent_id (DWB-426)

Revision ID: dwb426a1b2c3
Revises: dwb424a1b2c3
Create Date: 2026-06-22 22:30:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted.

Nullable FK to agents.id. NULL = a project-wide alert with no specific
recipient (every historical alert + the stale/rework/test alerts). Scoring
carrot/stick broadcasts (DWB-426/427) set it so each project agent gets a
personalized row. Backward-compatible: existing rows stay NULL.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb426a1b2c3"
down_revision: Union[str, None] = "dwb424a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "alerts",
        sa.Column("recipient_agent_id", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        op.f("ix_alerts_recipient_agent_id"),
        "alerts",
        ["recipient_agent_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_alerts_recipient_agent_id",
        "alerts",
        "agents",
        ["recipient_agent_id"],
        ["id"],
    )


def downgrade() -> None:
    # Resolve the FK name at runtime so down works whether the schema came from
    # this migration (named constraint) or from Base.metadata.create_all (the
    # test DB gets an autogenerated name).
    bind = op.get_bind()
    row = bind.execute(
        sa.text(
            "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'alerts' "
            "AND COLUMN_NAME = 'recipient_agent_id' "
            "AND REFERENCED_TABLE_NAME = 'agents'"
        )
    ).fetchone()
    if row is not None:
        op.drop_constraint(row.CONSTRAINT_NAME, "alerts", type_="foreignkey")
    op.drop_index(op.f("ix_alerts_recipient_agent_id"), table_name="alerts")
    op.drop_column("alerts", "recipient_agent_id")
