# Path: alembic/versions/dwb417a1b2c3_add_tool_actions_table.py
# File: dwb417a1b2c3_add_tool_actions_table.py
# Created: 2026-06-22
# Purpose: Create tool_actions table (DWB-417) - deterministic PostToolUse capture
# Caller: alembic upgrade head
# Callees: alembic.op, tool_actions table
# Data In: existing schema at dwb384d6f1a2c4
# Data Out: tool_actions table
# Last Modified: 2026-06-22

"""add tool_actions table (DWB-417)

Revision ID: dwb417a1b2c3
Revises: dwb384d6f1a2c4
Create Date: 2026-06-22 18:30:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted for new tables.

Schema:
  tool_actions
    id            BIGINT PK
    agent_id      BIGINT NULL  FK agents.id        (indexed)
    session_id    VARCHAR(255) NULL                (indexed; NOT unique)
    dwb_session_id BIGINT NULL FK dwb_sessions.id  (indexed)
    ticket_id     BIGINT NULL  FK tickets.id (ON DELETE CASCADE, indexed)
    tool_name     VARCHAR(255) NOT NULL
    target        VARCHAR(1024) NULL    (filled by sibling tickets)
    event_type    VARCHAR(50) NOT NULL DEFAULT 'tool_use'
    tool_metadata JSON NULL
    created_at    DATETIME NOT NULL DEFAULT now()

All context FKs are nullable: an unresolvable hook session_id still persists a
row with null context (delivery-gap tolerance). New table, no rows to backfill.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb417a1b2c3"
down_revision: Union[str, None] = "dwb384d6f1a2c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "tool_actions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.BigInteger(), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("dwb_session_id", sa.BigInteger(), nullable=True),
        sa.Column("ticket_id", sa.BigInteger(), nullable=True),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column("target", sa.String(length=1024), nullable=True),
        sa.Column(
            "event_type",
            sa.String(length=50),
            nullable=False,
            server_default="tool_use",
        ),
        sa.Column("tool_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["dwb_session_id"], ["dwb_sessions.id"]),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tool_actions_agent_id"), "tool_actions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_actions_session_id"),
        "tool_actions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tool_actions_dwb_session_id"),
        "tool_actions",
        ["dwb_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tool_actions_ticket_id"),
        "tool_actions",
        ["ticket_id"],
        unique=False,
    )


def downgrade() -> None:
    # drop_table removes the table's own indexes and FK constraints on MySQL.
    op.drop_table("tool_actions")
