# Path: alembic/versions/dwb424a1b2c3_add_scoring_tables.py
# File: dwb424a1b2c3_add_scoring_tables.py
# Created: 2026-06-22
# Purpose: Create score_event ledger + agent_score derived cache (DWB-424)
# Caller: alembic upgrade head
# Callees: alembic.op, score_event table, agent_score table
# Data In: existing schema at dwb417a1b2c3
# Data Out: score_event table, agent_score table
# Last Modified: 2026-06-22

"""add scoring tables (DWB-424)

Revision ID: dwb424a1b2c3
Revises: dwb417a1b2c3
Create Date: 2026-06-22 19:30:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted for new tables.

Schema:
  score_event (append-only ledger, source of truth)
    id BIGINT PK
    project_id      BIGINT NOT NULL FK projects.id (indexed)
    sprint_id       BIGINT NULL     FK sprints.id  (indexed)
    subject_agent_id BIGINT NOT NULL FK agents.id  (indexed)
    delta           INTEGER NOT NULL
    source          ENUM(auto,human,peer) NOT NULL
    trigger_type    ENUM(ticket_closed,rework,test_failure,stale,
                         zero_token_close,gate_miss,forgot,carrot,stick,
                         peer_grant,peer_demerit) NOT NULL
    actor_agent_id  BIGINT NULL FK agents.id
    actor_cost      INTEGER NOT NULL DEFAULT 0
    reason          VARCHAR(500) NULL  (auto self-describes; human/peer may omit)
    ref_type        VARCHAR(50) NULL
    ref_id          BIGINT NULL
    reverted_by     BIGINT NULL FK score_event.id (self-ref; corrections)
    created_at      DATETIME NOT NULL DEFAULT now()

  agent_score (derived cache, rebuildable from score_event)
    agent_id   BIGINT PK part FK agents.id
    project_id BIGINT PK part FK projects.id
    reputation INTEGER NOT NULL DEFAULT 0
    influence  INTEGER NOT NULL DEFAULT 0
    updated_at DATETIME NOT NULL DEFAULT now()

New tables, no rows to backfill.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb424a1b2c3"
down_revision: Union[str, None] = "dwb417a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "score_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("sprint_id", sa.BigInteger(), nullable=True),
        sa.Column("subject_agent_id", sa.BigInteger(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("auto", "human", "peer", name="scoresource"),
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            sa.Enum(
                "ticket_closed",
                "rework",
                "test_failure",
                "stale",
                "zero_token_close",
                "gate_miss",
                "forgot",
                "carrot",
                "stick",
                "peer_grant",
                "peer_demerit",
                name="scoretriggertype",
            ),
            nullable=False,
        ),
        sa.Column("actor_agent_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "actor_cost", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("ref_type", sa.String(length=50), nullable=True),
        sa.Column("ref_id", sa.BigInteger(), nullable=True),
        sa.Column("reverted_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.ForeignKeyConstraint(["sprint_id"], ["sprints.id"]),
        sa.ForeignKeyConstraint(["subject_agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["actor_agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["reverted_by"], ["score_event.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_score_event_project_id"), "score_event", ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_score_event_sprint_id"), "score_event", ["sprint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_score_event_subject_agent_id"), "score_event",
        ["subject_agent_id"], unique=False,
    )

    op.create_table(
        "agent_score",
        sa.Column("agent_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "reputation", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "influence", sa.Integer(), nullable=False, server_default="0"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("agent_id", "project_id"),
    )


def downgrade() -> None:
    # drop_table removes each table's own indexes and FK constraints on MySQL.
    # agent_score first (no dependents), then score_event (self-FK drops with
    # the table).
    op.drop_table("agent_score")
    op.drop_table("score_event")
