# Path: alembic/versions/dwb481a1b2c3_session_summary_and_entity_keywords.py
# File: dwb481a1b2c3_session_summary_and_entity_keywords.py
# Created: 2026-06-25
# Purpose: Add dwb_sessions.summary (JSON) + create the generic entity_keywords table (DWB-481)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb463a1b2c3
# Data Out: dwb_sessions.summary column + entity_keywords table (two indexes)
# Last Modified: 2026-06-25

"""session summary JSON + generic entity_keywords table (DWB-481)

Revision ID: dwb481a1b2c3
Revises: dwb463a1b2c3
Create Date: 2026-06-25 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs and is not trusted for new tables.

Substrate for Epic S74 session write-ups:
- dwb_sessions.summary: nullable JSON holding the structured bulleted write-up
  produced by the synthesizer (DWB-483). Distinct from the existing <=80-char
  headline; nullable so existing rows are untouched and only synthesized
  sessions carry it.
- entity_keywords: a GENERIC weighted keyword table. (entity_type, entity_id)
  is a polymorphic pointer (no hard FK) so the table is not bound to sessions;
  this sprint only entity_type='dwb_session' rows are written. `weight` is the
  per-entity occurrence count from the deterministic extractor (DWB-482).
  Two indexes per spec: single-column on `keyword` (term lookup across
  entities) and composite on (entity_type, entity_id) (all keywords for one
  entity in a single indexed scan).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb481a1b2c3"
down_revision: Union[str, None] = "dwb463a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable JSON column; no server_default needed (existing rows stay NULL).
    op.add_column(
        "dwb_sessions",
        sa.Column("summary", sa.JSON(), nullable=True),
    )

    op.create_table(
        "entity_keywords",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("keyword", sa.String(length=255), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_entity_keywords_keyword",
        "entity_keywords",
        ["keyword"],
        unique=False,
    )
    op.create_index(
        "ix_entity_keywords_entity",
        "entity_keywords",
        ["entity_type", "entity_id"],
        unique=False,
    )


def downgrade() -> None:
    # drop_table removes the table's own indexes on MySQL.
    op.drop_table("entity_keywords")
    op.drop_column("dwb_sessions", "summary")
