# Path: alembic/versions/dwb593a1b2c3_memory_transitions.py
# File: dwb593a1b2c3_memory_transitions.py
# Created: 2026-09-30 (DWB-593)
# Purpose: Make the outage state unreachable - widen projects.memory_mode with
#          the two transition states and add memory_transitions, one row per
#          candidate entry, so a mode change is the END of a pipeline rather
#          than a flag flip.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb584a1b2c3
# Data Out: projects.memory_mode widened, memory_transition_runs and
#           memory_transitions tables
# Last Modified: 2026-09-30 (DWB-593)

"""memory transitions: adopting/reverting states + per-entry pipeline (DWB-593)

Revision ID: dwb593a1b2c3
Revises: dwb584a1b2c3
Create Date: 2026-09-30 00:00:00.000000

Hand-written. Autogenerate does not detect ENUM widenings AT ALL, so an
autogenerated diff for this migration would be silently empty for half of it.

WHAT BUG THIS FIXES, AND THE FRAMING MATTERS MORE THAN THE CODE. Flipping
`memory_mode` straight to `human_memory` sealed the flat file (DWB-589) against
an empty store, so every agent on that project spawned amnesiac until someone
flipped it back.

THE SEAL IS NOT THE DEFECT AND IS NOT TOUCHED BY THIS MIGRATION. It does
exactly what DWB-589 specified, instantly and completely, which was right for a
flag nobody could flip without a migration behind it. What was missing is that
nothing enforced that precondition. So the fix is to make the state the seal
fires in UNREACHABLE, not to give the seal exceptions. A seal with exceptions
leaks on a path nobody tested, and hard rule 1 exists to stop two memories both
looking authoritative.

THE NO-OUTAGE PROPERTY COMES FREE, AND IT IS WORTH KNOWING WHY. There is
exactly one `memory_mode` predicate in the backend, at
`app/services/memory_mode.py`, and it reads `== MemoryMode.human_memory` rather
than `!= MemoryMode.stock`. So a project in `adopting` or `reverting` is simply
not sealed: stock stays authoritative for reads and writes throughout, and an
agent spawning mid-transition notices nothing. Anyone "tidying" that predicate
to `!= stock` re-creates the original outage on a new path; a test asserts it.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb593a1b2c3"
down_revision: Union[str, Sequence[str], None] = "dwb584a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The tier vocabulary, reused rather than re-declared. One definition of what a
# tier is; `raw` is carried because the enum is shared, and the service refuses
# it as a PROPOSAL (a proposal is a judgement, and `raw` is the absence of one).
_TIERS = ("raw", "core", "scar", "scar_context_bound", "working")

_MODE_OLD = "ENUM('stock','human_memory')"
_MODE_NEW = "ENUM('stock','human_memory','adopting','reverting')"


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. Widen the mode enum.
    #
    # The two new values are APPENDED, after the existing two. MySQL stores an
    # ENUM as the ordinal of its value, so appending leaves every stored row
    # byte-identical and rewrites nothing. Inserting in the middle would
    # renumber `human_memory` and silently change what existing rows mean,
    # which is the kind of corruption that reads as fine until someone queries
    # by value.
    # ------------------------------------------------------------------
    op.execute(
        f"ALTER TABLE projects MODIFY COLUMN memory_mode {_MODE_NEW} "
        "NOT NULL DEFAULT 'stock'"
    )

    # ------------------------------------------------------------------
    # 2. memory_transitions: ONE ROW PER CANDIDATE ENTRY.
    #
    # The point of the row-per-entry shape, in Miles's words: "I don't want to
    # leave it to just a giant context list." Nobody is ever handed a whole
    # memory file and asked to sort it out. It also makes the work resumable
    # and auditable, which a single in-flight flag cannot be.
    # ------------------------------------------------------------------
    # ------------------------------------------------------------------
    # 2a. memory_transition_runs: THE RUN ITSELF, one row per transition.
    #
    # Added on TL ruling after the entry table alone proved insufficient, and
    # the reason is the one that only shows up later: a project that adopts,
    # reverts and adopts AGAIN has entry rows that nothing distinguishes. With
    # no run to hang them off, either the earlier rows are deleted, destroying
    # the audit trail the design promised, or they are kept and every count the
    # guard and the overlay make is wrong from the second transition onward.
    # A defect with no detector.
    #
    # `enumerated_at` IS THE PRECONDITION THE FIRST VERSION WAS MISSING. A
    # cutover guard that only asks "are any entries unfinished" passes
    # trivially when there are NO entries, so stock -> adopting -> human_memory
    # sealed the flat file against an empty store in two calls: the original
    # bug, through the machine built to prevent it. Zero entries is ambiguous
    # between "enumeration ran and found nothing", which is a legitimate
    # cutover for a project with no memory, and "enumeration never ran", which
    # is the bug. A count cannot separate them; a timestamp can.
    #
    # NO ENTRY OR AGENT COUNTS ARE STORED HERE. They are derived, and a stored
    # count is a second authoritative copy that drifts the moment a row changes
    # state without the header being updated - the same defect as a stored
    # score, which this lane has already refused twice. Readers aggregate.
    # ------------------------------------------------------------------
    op.create_table(
        "memory_transition_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("adopt", "revert", name="memorytransitiondirection"),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum("open", "completed", "aborted", name="memorytransitionrunstate"),
            nullable=False,
            server_default="open",
        ),
        sa.Column(
            "started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        # NULL until the enumerator has run for THIS run. The cutover guard
        # refuses while it is NULL.
        sa.Column("enumerated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("aborted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        # At most one OPEN run per project, enforced by the database rather than
        # by a read-check-write. MySQL has no partial indexes, so this is the
        # dwb_sessions pattern: a STORED generated column that is 1 while open
        # and NULL otherwise, plus a composite UNIQUE. MySQL treats NULL as
        # distinct in a UNIQUE index, so closed runs never collide.
        sa.Column(
            "is_open",
            sa.Integer(),
            sa.Computed("(CASE WHEN state = 'open' THEN 1 ELSE NULL END)", persisted=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "is_open", name="uq_transition_run_one_open"),
    )
    op.create_index(
        "ix_memory_transition_runs_project", "memory_transition_runs", ["project_id"]
    )

    op.create_table(
        "memory_transitions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("agent_id", sa.BigInteger(), nullable=False),
        # NOT NULL: an entry row without a run is the orphan this table was
        # reshaped to make impossible. `direction` moved onto the run, where it
        # is stated once instead of repeated on every entry.
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        # pending -> proposed -> decided -> written, with skipped and journaled
        # as the other two terminal states. The cutover guard reads this: a
        # project may not flip while any row is non-terminal.
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "proposed",
                "decided",
                "written",
                "skipped",
                "journaled",
                name="memorytransitionstate",
            ),
            nullable=False,
            server_default="pending",
        ),
        # The slice of the flat file this row is about. Nullable because a
        # revert direction has no flat-file source; its source is a row.
        sa.Column("source_excerpt", sa.Text(), nullable=True),
        sa.Column("proposed_tier", sa.Enum(*_TIERS, name="memorytier"), nullable=True),
        sa.Column("decided_tier", sa.Enum(*_TIERS, name="memorytier"), nullable=True),
        # Who decided, as free text rather than an FK: the decider may be an
        # agent, a human, or a rule, and an agents FK would force the first.
        sa.Column("decided_by", sa.String(length=255), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        # The agent_memories row this produced, once it is written. NULL until
        # then, and NULL forever for skipped and journaled rows.
        sa.Column("target_memory_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(
            ["run_id"], ["memory_transition_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["target_memory_id"], ["agent_memories.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # The cutover guard's query: every non-terminal row for a project.
    op.create_index(
        "ix_memory_transitions_project_state",
        "memory_transitions",
        ["project_id", "state"],
    )
    op.create_index(
        "ix_memory_transitions_agent_state", "memory_transitions", ["agent_id", "state"]
    )
    op.create_index(
        "ix_memory_transitions_target_memory_id",
        "memory_transitions",
        ["target_memory_id"],
    )
    op.create_index("ix_memory_transitions_run_state", "memory_transitions", ["run_id", "state"])


def downgrade() -> None:
    # No explicit drop_index before drop_table: MySQL refuses to drop an index a
    # foreign key still needs (errno 1553), and drop_table removes the table's
    # indexes with it. See ARCHITECTURE section 9.
    op.drop_table("memory_transitions")
    op.drop_table("memory_transition_runs")

    # RESOLVE IN-FLIGHT PROJECTS BEFORE NARROWING THE ENUM, because MySQL
    # refuses to remove a value some row still holds. Each project lands on the
    # store that is ACTUALLY authoritative for it at that moment, so no agent's
    # memory changes hands on a downgrade:
    #
    #   adopting  -> stock          it never cut over; stock is still its memory
    #   reverting -> human_memory   it never cut back; the store is still its memory
    #
    # The alternative, refusing to downgrade while a transition is open, would
    # make this migration un-round-trippable in exactly the state the feature
    # exists to create. TL ruling, 2026-09-30.
    op.execute("UPDATE projects SET memory_mode = 'stock' WHERE memory_mode = 'adopting'")
    op.execute(
        "UPDATE projects SET memory_mode = 'human_memory' WHERE memory_mode = 'reverting'"
    )
    op.execute(
        f"ALTER TABLE projects MODIFY COLUMN memory_mode {_MODE_OLD} "
        "NOT NULL DEFAULT 'stock'"
    )
