# Path: alembic/versions/dwb505a1b2c3_widen_token_columns_to_bigint.py
# File: dwb505a1b2c3_widen_token_columns_to_bigint.py
# Created: 2026-07-28
# Purpose: Widen all aggregating token columns from INT to BIGINT (DWB-505) so a large session rollup can no longer overflow the close UPDATE
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb481a1b2c3
# Data Out: dwb_sessions.total_tokens, hook_sessions.total_tokens, tracking_log.tokens all BIGINT
# Last Modified: 2026-07-28

"""widen token columns to BIGINT (DWB-505)

Revision ID: dwb505a1b2c3
Revises: dwb481a1b2c3
Create Date: 2026-07-28 00:00:00.000000

Hand-written, not autogenerated. Per project rule, MySQL alembic autogenerate
does NOT detect column TYPE changes (INT -> BIGINT) at all, so an autogenerated
migration for this would be empty. It also emits spurious drop_index ops on
error_logs. This migration is authored by hand.

Root cause (DWB-505): dwb_sessions.total_tokens was INT (signed max
2,147,483,647). DWB session 65 rolled up 5,479,293,087 tokens, so the close
UPDATE raised MySQL error 1264 "Out of range value" and every close attempt
500'd. The same overflow silently poisoned the idle-sweeper batch.

Every column that aggregates a token SUM is widened to BIGINT here. Columns
that already store a token SUM as BIGINT (tickets.tokens_used,
projects.tl_overhead_tokens, projects.pm_overhead_tokens) were audited and are
already correct - they are intentionally NOT touched. hook_sessions.total_tokens
holds a per-session figure but is the summand of the dwb_sessions rollup, and
tracking_log.tokens is a per-event figure summed into tracking summaries, so
both are widened for consistency and headroom.

Fresh-install safe: the ORM models declare these columns as BigInteger
(create_all on a fresh DB produces BIGINT directly), so this migration only
ever runs against an existing INT schema. Re-running it against an
already-BIGINT column is a no-op MODIFY on MySQL.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb505a1b2c3"
down_revision: Union[str, None] = "dwb481a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # dwb_sessions.total_tokens - the column that actually overflowed. Carries a
    # server_default of 0 in the live schema; preserve it across the MODIFY.
    op.alter_column(
        "dwb_sessions",
        "total_tokens",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )

    # hook_sessions.total_tokens - summand of the dwb_sessions rollup. No server
    # default in the live schema.
    op.alter_column(
        "hook_sessions",
        "total_tokens",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )

    # tracking_log.tokens - per-event token count summed into tracking totals.
    op.alter_column(
        "tracking_log",
        "tokens",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )


def downgrade() -> None:
    # Narrow back to INT. NOTE: any row whose value exceeds the INT range would
    # be truncated by MySQL on this MODIFY; the downgrade is provided for
    # completeness and is not expected to run against real data.
    op.alter_column(
        "tracking_log",
        "tokens",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "hook_sessions",
        "total_tokens",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "dwb_sessions",
        "total_tokens",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
