# Path: alembic/versions/dwb527a1b2c3_add_project_nodeified_at.py
# File: dwb527a1b2c3_add_project_nodeified_at.py
# Created: 2026-09-14 (DWB-527)
# Purpose: Add projects.nodeified_at - the timestamp of the last operator-invoked
#          nodeify full pass (rebuild nodes from memory + docs + git). Nullable;
#          null means the project has never been nodeified.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb522a1b2c3
# Data Out: projects.nodeified_at DATETIME NULL
# Last Modified: 2026-09-14 (DWB-527)

"""add projects.nodeified_at (DWB-527)

Revision ID: dwb527a1b2c3
Revises: dwb522a1b2c3
Create Date: 2026-09-14 00:00:00.000000

Hand-written, not autogenerated (project rules). Nullable column, no backfill
needed - a null value is the correct "never nodeified" state for existing rows.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb527a1b2c3"
down_revision: Union[str, Sequence[str], None] = "dwb522a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "projects",
        sa.Column("nodeified_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("projects", "nodeified_at")
