# Path: alembic/versions/dwb537a1b2c3_stick_redemption.py
# File: dwb537a1b2c3_stick_redemption.py
# Created: 2026-09-15 (DWB-537)
# Purpose: Stick redemption ledger support: widen score_event.trigger_type with
#          'redemption' and add the STORED generated column redemption_of plus its
#          unique index, the race-safe once-per-stick guard.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb527a1b2c3
# Data Out: score_event.trigger_type ENUM(+redemption), score_event.redemption_of
#           BIGINT GENERATED ALWAYS AS (...) STORED, UNIQUE uq_score_event_redemption_of
# Last Modified: 2026-09-15 (DWB-537)

"""stick redemption: trigger enum + unique redemption_of guard (DWB-537)

Revision ID: dwb537a1b2c3
Revises: dwb527a1b2c3
Create Date: 2026-09-15 00:00:00.000000

Hand-written, not autogenerated (project rules): MySQL autogenerate does not
emit ENUM widenings, and generated columns need the exact expression.

The guard: a redemption is one score_event row with trigger_type='redemption',
ref_type='score_event', ref_id=<stick id>. redemption_of mirrors ref_id for
exactly those rows and is NULL for every other row. MySQL unique indexes treat
NULLs as distinct, so the UNIQUE index only ever compares redemption rows,
making a double grant for the same stick impossible even under a race (the
losing INSERT fails with a duplicate-key error, which the service turns into
"already redeemed").

Downgrade drops the index + column and narrows the ENUM. The narrowing MODIFY
fails if any redemption rows exist (MySQL refuses the truncation); revert or
delete those rows first if you must roll back.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "dwb537a1b2c3"
down_revision: Union[str, Sequence[str], None] = "dwb527a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Full value list AFTER this migration (order matches the Python enum).
_TRIGGER_NEW = (
    "'ticket_closed','rework','test_failure','stale','zero_token_close',"
    "'gate_miss','forgot','carrot','stick','peer_grant','peer_demerit',"
    "'audit_grant','audit_demerit','redemption'"
)

# Pre-DWB-537 value list (for downgrade).
_TRIGGER_OLD = (
    "'ticket_closed','rework','test_failure','stale','zero_token_close',"
    "'gate_miss','forgot','carrot','stick','peer_grant','peer_demerit',"
    "'audit_grant','audit_demerit'"
)

_GENERATED_EXPR = (
    "CASE WHEN trigger_type = 'redemption' AND ref_type = 'score_event' "
    "THEN ref_id ELSE NULL END"
)


def upgrade() -> None:
    op.execute(
        f"ALTER TABLE score_event MODIFY COLUMN trigger_type "
        f"ENUM({_TRIGGER_NEW}) NOT NULL"
    )
    op.execute(
        f"ALTER TABLE score_event ADD COLUMN redemption_of BIGINT "
        f"GENERATED ALWAYS AS ({_GENERATED_EXPR}) STORED NULL"
    )
    op.execute(
        "ALTER TABLE score_event ADD UNIQUE INDEX uq_score_event_redemption_of "
        "(redemption_of)"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE score_event DROP INDEX uq_score_event_redemption_of")
    op.execute("ALTER TABLE score_event DROP COLUMN redemption_of")
    op.execute(
        f"ALTER TABLE score_event MODIFY COLUMN trigger_type "
        f"ENUM({_TRIGGER_OLD}) NOT NULL"
    )
