"""DWB-580: transcript_bytes on hook_sessions

Revision ID: dwb580a1b2c3
Revises: dwb564a1b2c3
Create Date: 2026-09-16

Hand-written rather than autogenerated: autogenerate on this schema invents
spurious drop_index operations on error_logs every time (see
.claude/project_rules_worker.md), and this is a single nullable column.

Nullable with no server_default on purpose. The column records how much of a
transcript the stored token total accounts for, so for every existing row the
honest value is "unknown", and NULL says that. Backfilling a number here would
assert we had accounted for bytes we never read.
"""
from alembic import op
import sqlalchemy as sa

revision = "dwb580a1b2c3"
down_revision = "dwb564a1b2c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "hook_sessions",
        sa.Column("transcript_bytes", sa.BigInteger(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("hook_sessions", "transcript_bytes")
