# Path: alembic/versions/dwb584a1b2c3_human_memory_substrate.py
# File: dwb584a1b2c3_human_memory_substrate.py
# Created: 2026-09-29 (DWB-584)
# Purpose: Substrate for human_memory mode - the journal_entries and
#          agent_memories tables, the projects.memory_mode toggle and its
#          schema version, plus (unrelated, see below) the top-off columns and
#          the per-session prompt counter.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb581a1b2c3
# Data Out: journal_entries table, agent_memories table, projects.memory_mode,
#           projects.memory_schema_version, projects.topoff_enabled,
#           projects.topoff_interval, hook_sessions.prompt_count
# Last Modified: 2026-09-29 (DWB-584 amendment: cost/caught_by/surprised moved
#                from journal_entries onto agent_memories, per spec section 6's
#                second amendment. Edited in place rather than chained behind a
#                follow-up revision: TL ruling, tables empty and unread.)

"""human_memory substrate: agent_memories, journal_entries, memory_mode (DWB-584)

Revision ID: dwb584a1b2c3
Revises: dwb581a1b2c3
Create Date: 2026-09-29 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate is not
trusted here (spurious drop_index ops on error_logs, unreliable ENUM emission,
missed widenings).

Source: docs/human_memory_spec.md, sections 3 and 6, section 6 as AMENDED
2026-09-29. The amendment removed a `score` column and replaced a
`last_reinforced` timestamp with a session reference; this migration is written
against the amended text.

THERE IS NO SCORE COLUMN AND THERE MUST NEVER BE ONE. Section 3 rules that the
score is a pure function of (tier, sessions_since_reinforced), derived at read
time. A stored score is a second authoritative copy of a derived fact: it needs
every row rewritten every session and it drifts out of sync with the rule, where
a derived score cannot disagree with itself. The same reasoning excludes a
stored band and a stored sessions_since_reinforced. What IS persisted: tier, the
two session references, fired_count and context_key.

THE CLOCK IS SESSIONS, NOT DAYS. That is why reinforcement is
last_reinforced_session_id, a FK to dwb_sessions, rather than a timestamp.
created_at / updated_at on agent_memories are ordinary bookkeeping and are not
the clock.

Table order is forced: journal_entries is created first because
agent_memories.source_journal_id points at it. The reverse FK does not exist, on
purpose - a memory can be evicted without stranding the story it came from.

Fresh-install safe: the ORM models declare both tables, so create_all on a fresh
DB produces them directly and this migration only runs against an existing
schema. A fresh clone running `alembic upgrade head` from base gets the same
result through this file.

Existing databases: every added column is NOT NULL with a server_default, so
existing rows take the default without a backfill pass. memory_mode defaults to
`stock`, which is zero behaviour change for every agent.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb584a1b2c3"
down_revision: Union[str, Sequence[str], None] = "dwb581a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # journal_entries - created BEFORE agent_memories, which references it.
    # ------------------------------------------------------------------
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.BigInteger(), nullable=False),
        # Nullable for the same reason hook_sessions.dwb_session_id is: an entry
        # can be written outside any open DWB session.
        sa.Column("dwb_session_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "entered_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        # Free list of strings, and half of this table's retrieval path (spec
        # section 5: tags plus date plus term, never a full scan). JSON rather
        # than a child table because nothing joins on a tag yet.
        #
        # cost, caught_by and surprised are DELIBERATELY NOT HERE. Spec section
        # 6's second amendment moved them onto agent_memories; see the comment
        # on that table below.
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column(
            "retrieval_count", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["dwb_session_id"], ["dwb_sessions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_journal_entries_agent_id", "journal_entries", ["agent_id"])
    op.create_index(
        "ix_journal_entries_dwb_session_id", "journal_entries", ["dwb_session_id"]
    )
    op.create_index(
        "ix_journal_entries_agent_entered",
        "journal_entries",
        ["agent_id", "entered_at"],
    )

    # ------------------------------------------------------------------
    # agent_memories
    #
    # `raw` is on the tier enum but is NOT one of the spec's tiers. It is the
    # state DWB-586 appends a row in, before consolidation has judged it: spec
    # section 4 rules that a session appends RAW and unsorted, because tiering
    # in the moment rubber-stamps in-the-moment salience, which is the judgment
    # consolidation exists to make.
    #
    # It is an enum VALUE rather than a nullable tier (DWB-584 ruling). NULL in
    # this schema already means "we do not know" - hook_sessions.ticket_source
    # documents that convention. An untiered row is a known state a writer
    # chose, not an unknown. Making it a value also forces the scoring query to
    # NAME it in order to exclude it, where a nullable column would let a join
    # or an IS NOT NULL drop those rows silently. Untiered rows are excluded
    # from scoring until consolidation tiers them.
    #
    # There is no `journal` member: the journal is its own table above.
    # ------------------------------------------------------------------
    op.create_table(
        "agent_memories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "raw",
                "core",
                "scar",
                "scar_context_bound",
                "working",
                name="memorytier",
            ),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        # What a context-bound scar is bound TO. NULL for every other tier. The
        # SCAN reads this to ask whether the context is still alive.
        sa.Column("context_key", sa.String(length=255), nullable=True),
        # cost, caught_by and surprised live HERE and not on journal_entries
        # (spec section 6, second amendment, 2026-09-29). Sections 4 and 6
        # disagreed and the tie was broken by asking what READS each field:
        # section 2 gates the SCAN on cost and the SCAN runs over scars, which
        # are memory rows; section 4 justifies caught_by through a query over
        # lessons; surprised is prediction error, which section 1 makes the
        # driver of encoding strength.
        #
        # They are not ALSO on journal_entries, deliberately. Section 7 opens by
        # naming two stores that both look authoritative and disagree as the
        # failure mode, and a tag duplicated across the two is that in
        # miniature. All three nullable: section 4 says tag only what the moment
        # knows, so untagged is the normal case.
        sa.Column(
            "cost", sa.Enum("none", "low", "high", name="memorycost"), nullable=True
        ),
        sa.Column(
            "caught_by",
            sa.Enum("me", "worker", "human", "ci", name="memorycaughtby"),
            nullable=True,
        ),
        # Tri-state on purpose: True, False, and "nobody said". NULL is not False.
        sa.Column("surprised", sa.Boolean(), nullable=True),
        # Both nullable: a memory can be created or reinforced outside any open
        # DWB session, and a row carried in from stock memory has no
        # originating session at all.
        sa.Column("created_session_id", sa.BigInteger(), nullable=True),
        sa.Column("last_reinforced_session_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "fired_count", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        # One direction only: journal_entries does not point back, so a memory
        # can be evicted without stranding the story it came from (spec section
        # 7 hard rule 4, anything leaving memory lands in the journal first).
        sa.Column("source_journal_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"]),
        sa.ForeignKeyConstraint(["created_session_id"], ["dwb_sessions.id"]),
        sa.ForeignKeyConstraint(["last_reinforced_session_id"], ["dwb_sessions.id"]),
        sa.ForeignKeyConstraint(["source_journal_id"], ["journal_entries.id"]),
        sa.PrimaryKeyConstraint("id"),
        # NOTE FOR THE SCORING QUERY DWB-585 BUILDS ON THESE COLUMNS. The
        # sessions-since-reinforced count runs over hook_sessions, where BOTH
        # agent_id and dwb_session_id are nullable: historical rows predate the
        # DWB session model and must remain valid. COUNT(DISTINCT
        # dwb_session_id) silently skips NULLs, and that is the INTENDED
        # behaviour, not an accident - a hook session never linked to a DWB
        # session is not an experience that should tick the decay clock.
        # Document it at the query site so the next reader does not "fix" it.
    )
    op.create_index("ix_agent_memories_agent_id", "agent_memories", ["agent_id"])
    op.create_index(
        "ix_agent_memories_last_reinforced_session_id",
        "agent_memories",
        ["last_reinforced_session_id"],
    )
    # The spawn-time load: every memory for one agent, tier-ordered.
    op.create_index(
        "ix_agent_memories_agent_tier", "agent_memories", ["agent_id", "tier"]
    )

    # ------------------------------------------------------------------
    # projects.memory_mode + memory_schema_version
    #
    # Default `stock` means an existing DB upgrades with zero behaviour change
    # for every agent. The mode never leaves beta and is versioned, which is
    # what memory_schema_version stamps: v1 content stays readable by v2
    # tooling.
    # ------------------------------------------------------------------
    op.add_column(
        "projects",
        sa.Column(
            "memory_mode",
            sa.Enum("stock", "human_memory", name="memorymode"),
            nullable=False,
            server_default="stock",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "memory_schema_version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
    )

    # ------------------------------------------------------------------
    # TOP-OFF. THESE COLUMNS ARE DELIBERATELY UNRELATED TO THE MEMORY COLUMNS
    # BESIDE THEM, AND THAT IS LOAD-BEARING RATHER THAN A FOOTNOTE.
    #
    # Miles ruled top-off INDEPENDENT of memory mode, and spec section 8 reached
    # the same conclusion: "do not gate it. It is orthogonal, about repetition
    # and drift, not memory structure. Only consolidation is mode-specific."
    #
    # They share this migration and the projects table with memory_mode for
    # DELIVERY reasons only: DWB-584 held the sprint's single migration slot,
    # so folding them in was free today and would have cost a second migration
    # tomorrow. Zero dependency runs between the two features. DWB-590's logic
    # must NOT read memory_mode, and top-off must work on a project in `stock`
    # mode. Schema colocation is not feature coupling.
    #
    # hook_sessions.prompt_count is the third column in this group. A stored
    # counter, not a derived one, and that was checked rather than defaulted:
    # nothing in the schema records a prompt. hook_sessions is one row per
    # Claude Code session, not per prompt, and handle_user_prompt writes no row
    # on any of its noop paths, so there is no existing count and no trace to
    # count from. Keyed by the session_id the hook payload already carries,
    # which makes the counter per Claude Code session and therefore per agent,
    # matching the unit the top-off is injected into. The edge where a prompt
    # arrives before SessionStart has been processed - no row to count against -
    # needs a defined behaviour in DWB-590, not a column here.
    # ------------------------------------------------------------------
    op.add_column(
        "projects",
        sa.Column(
            "topoff_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "topoff_interval",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("10"),
        ),
    )
    op.add_column(
        "hook_sessions",
        sa.Column(
            "prompt_count",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )


def downgrade() -> None:
    op.drop_column("hook_sessions", "prompt_count")
    op.drop_column("projects", "topoff_interval")
    op.drop_column("projects", "topoff_enabled")
    op.drop_column("projects", "memory_schema_version")
    op.drop_column("projects", "memory_mode")

    # NO explicit drop_index calls before these drop_table calls, and that is
    # deliberate rather than an omission. Every index on both tables covers a
    # foreign key column, and MySQL REFUSES to drop an index a foreign key
    # needs (errno 1553). Dropping them by hand raised that error here, and
    # because DDL is non-transactional the failed downgrade had already
    # committed the column drops above, leaving the database half-migrated with
    # alembic_version still pointing at this revision. drop_table removes the
    # table's indexes with it, so there is nothing left to tidy.
    #
    # agent_memories first: it carries the FK to journal_entries.
    op.drop_table("agent_memories")
    op.drop_table("journal_entries")
