# Path: alembic/versions/dwb510a1b2c3_add_failure_record_reviewed.py
# File: dwb510a1b2c3_add_failure_record_reviewed.py
# Created: 2026-09-14
# Purpose: Add failure_records.reviewed (DWB-510) - the structured signal that replaces the fragile notes-text stub heuristic in the sprint-close failure gate; also merges the two open heads (dwb022a1b2c3, dwb505a1b2c3) into one.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at heads dwb022a1b2c3 + dwb505a1b2c3
# Data Out: failure_records.reviewed BOOLEAN NOT NULL DEFAULT 0, backfilled True where the row was edited after creation
# Last Modified: 2026-09-14

"""add failure_records.reviewed + merge heads (DWB-510)

Revision ID: dwb510a1b2c3
Revises: dwb022a1b2c3, dwb505a1b2c3
Create Date: 2026-09-14 00:00:00.000000

Hand-written, not autogenerated. Two independent branch tips were open
(dwb022a1b2c3 and dwb505a1b2c3, both applied to the live DB); this revision
takes both as its down_revision so it also merges them into a single head.

DWB-510: the sprint-close failure gate decided whether an auto-created rework
stub was "unreviewed" by matching the "Auto-detected" boilerplate in the notes
text. A PM who reviewed the record but left that boilerplate in the notes was
misclassified as unreviewed (close stayed blocked); inversely, rewriting the
notes could slip an unreviewed record past the gate. This adds a structured
`reviewed` flag the gate keys off instead.

Backfill: existing rows are set reviewed=True when updated_at > created_at, i.e.
the record was edited after its auto-creation (a PM touched it). Untouched
auto-stubs stay reviewed=False and keep blocking, preserving current behaviour
for genuinely-unreviewed rows while clearing the misclassification for edited
ones.

Fresh-install safe: the ORM model declares the column with a server_default of
0, so create_all on a fresh DB produces the column directly and this migration
only ever runs against an existing schema.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb510a1b2c3"
down_revision: Union[str, Sequence[str], None] = ("dwb022a1b2c3", "dwb505a1b2c3")
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL on a table with existing rows requires a server_default so the
    # backfill of existing rows is well-defined (project rule).
    op.add_column(
        "failure_records",
        sa.Column(
            "reviewed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    # Backfill: a row edited after auto-creation (updated_at strictly after
    # created_at) has been touched by a PM -> reviewed. Untouched auto-stubs
    # stay False and keep gating sprint close.
    op.execute(
        "UPDATE failure_records SET reviewed = 1 WHERE updated_at > created_at"
    )


def downgrade() -> None:
    op.drop_column("failure_records", "reviewed")
