# Path: alembic/versions/dwb564a1b2c3_add_agents_last_memory_write_at.py
# File: dwb564a1b2c3_add_agents_last_memory_write_at.py
# Created: 2026-09-16 (DWB-564)
# Purpose: Add agents.last_memory_write_at — a DB-recorded fact ("this agent's
#          memory-write endpoint was called at time T"), replacing the DWB-519
#          write-on-close gate's sole reliance on scanning memory.md for an ISO
#          heading. That heading-only path stayed correct only because condense
#          happens to stamp one; a condense to topic-only headings (the exact
#          shape DWB-560 encourages) or a plain compact (which stamps none)
#          reads a real writer as a non-writer. See memory_trace.py.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb549a1b2c3
# Data Out: agents.last_memory_write_at DATETIME NULL
# Last Modified: 2026-09-16 (DWB-564)

"""add agents.last_memory_write_at (DWB-564)

Revision ID: dwb564a1b2c3
Revises: dwb549a1b2c3
Create Date: 2026-09-16 00:00:00.000000

Hand-written, not autogenerated (project rules). Nullable column, no
backfill inside this migration — filesystem I/O (scanning each agent's
memory.md for its latest ISO heading) does not belong in a schema migration
that must stay valid independent of application code. Run
backend/scripts/backfill_last_memory_write_at.py once after this lands,
before relying on the column for the write-on-close gate. Until it's run
(or for any row it misses), memory_trace.agent_wrote_since falls back to the
original heading scan on a NULL — a pre-existing agent never reads as a
non-writer just because this column hasn't been populated for them yet.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb564a1b2c3"
down_revision: Union[str, Sequence[str], None] = "dwb549a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "agents",
        sa.Column("last_memory_write_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("agents", "last_memory_write_at")
