# Path: alembic/versions/dwb522a1b2c3_add_node_tables.py
# File: dwb522a1b2c3_add_node_tables.py
# Created: 2026-09-14 (DWB-522)
# Purpose: Create the nodes + node_pointers tables - LIGHT knowledge nodes (one
#          row per grounded normalized tag) and their pointers (WHERE the tag is
#          grounded: kind + ref + optional sha + line range). No edge table -
#          connections derive from shared pointer refs (DWB-523).
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb510a1b2c3
# Data Out: nodes table, node_pointers table
# Last Modified: 2026-09-14 (DWB-522)

"""add nodes + node_pointers tables (DWB-522)

Revision ID: dwb522a1b2c3
Revises: dwb510a1b2c3
Create Date: 2026-09-14 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate is not
trusted for new tables (spurious drop_index ops on error_logs, unreliable ENUM
emission).

A node is LIGHT (Miles ruling): the nodes row holds only the normalized tag, a
ranking weight (count of grounding pointers), and timestamps - never content.
node_pointers holds the WHERE: kind (domain enum), ref, and optional sha +
line_start/line_end for code/doc provenance. node_id is NOT NULL: a pointer only
exists for a tag that already cleared the 2-domain grounding rule, and deleting a
node cascades its pointers (ondelete CASCADE). tag is denormalized onto the
pointer for single-scan domain counting + shared-ref neighbor joins.

Fresh-install safe: the ORM models declare these tables, so create_all on a fresh
DB produces them directly and this migration only runs against an existing schema.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb522a1b2c3"
down_revision: Union[str, Sequence[str], None] = "dwb510a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "nodes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("tag", sa.String(length=255), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "tag", name="uq_nodes_project_tag"),
    )
    op.create_index("ix_nodes_project_id", "nodes", ["project_id"])
    op.create_index("ix_nodes_project_weight", "nodes", ["project_id", "weight"])

    op.create_table(
        "node_pointers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=False),
        sa.Column("tag", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "code", "memory", "doc", "ticket", "session",
                name="nodepointerkind",
            ),
            nullable=False,
        ),
        sa.Column("ref", sa.String(length=500), nullable=False),
        sa.Column("sha", sa.String(length=64), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=True),
        sa.Column("line_end", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_node_pointers_project_tag", "node_pointers", ["project_id", "tag"]
    )
    op.create_index(
        "ix_node_pointers_project_kind_ref",
        "node_pointers",
        ["project_id", "kind", "ref"],
    )
    op.create_index(
        "ix_node_pointers_project_ref", "node_pointers", ["project_id", "ref"]
    )
    op.create_index("ix_node_pointers_node_id", "node_pointers", ["node_id"])


def downgrade() -> None:
    op.drop_index("ix_node_pointers_node_id", table_name="node_pointers")
    op.drop_index("ix_node_pointers_project_ref", table_name="node_pointers")
    op.drop_index("ix_node_pointers_project_kind_ref", table_name="node_pointers")
    op.drop_index("ix_node_pointers_project_tag", table_name="node_pointers")
    op.drop_table("node_pointers")
    op.drop_index("ix_nodes_project_weight", table_name="nodes")
    op.drop_index("ix_nodes_project_id", table_name="nodes")
    op.drop_table("nodes")
