# Path: alembic/versions/dwb611a1b2c3_collapse_scar_context_bound.py
# File: dwb611a1b2c3_collapse_scar_context_bound.py
# Created: 2026-09-30 (DWB-611)
# Purpose: Collapse agent_memories.tier's `scar_context_bound` value into
#          `scar` - Miles's ruling is four buckets, all scars context-bound,
#          not a fifth value distinguishing which ones are. Retiers every
#          existing scar_context_bound row to scar, THEN narrows the column's
#          ENUM, so no row is left holding a value the column no longer
#          accepts.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb605a1b2c3
# Data Out: agent_memories.tier (ENUM narrowed by one value); agent_memories
#           rows previously tiered scar_context_bound
# Last Modified: 2026-09-30 (DWB-611)

"""Collapse scar_context_bound into scar (DWB-611)

Revision ID: dwb611a1b2c3
Revises: dwb605a1b2c3
Create Date: 2026-09-30 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate is not
trusted here (spurious drop_index ops on error_logs, unreliable ENUM emission,
missed widenings), and this migration reorders an ENUM value list, which
autogenerate does not reliably detect at all.

FROM THE HUMAN MEMORY AUDIT, 2026-09-30. Miles's ruling: four buckets, no more
no less, and ALL scars are context bound - there should never have been a
second tier value distinguishing "the ones that are" from "the ones that
aren't". The audit found the split load-bearing in three application-layer
places (which tier an agent could choose while adopting, whether context_key
got populated, which heading memory_revert rendered under) but the decay
curve was ALREADY identical for both values before this migration - so this
is purely a schema and application refactor, not a change to any score.

ORDER IS NOT OPTIONAL: DATA FIRST, THEN THE ENUM. Retiering every
scar_context_bound row to scar before narrowing the column's allowed values
is the only safe order. Narrowing the ENUM first would leave existing
scar_context_bound rows holding a value MySQL no longer accepts for that
column - reachable rows that silently corrupt on the next write, or fail to
load depending on strict-mode settings, either of which is worse than the
one-line UPDATE this order avoids needing.

`context_key` IS NOT TOUCHED HERE, DELIBERATELY. Every row being retiered
already carries whatever context_key memory_decide.py gave it (set when a
heading path was available, None otherwise); collapsing the tier changes
nothing about that column, and the ticket's "carry context_key forward for
ALL scar rows going forward, not a subset" is an application-layer change
(app/services/memory_decide.py, this same ticket) for rows written AFTER this
migration, not a backfill for rows written before it. A row filed as plain
`scar` before this migration never had a context_key and still does not;
inventing one now would fabricate a binding nobody ever named.

DOWNGRADE IS NOT A DATA RESTORE, AND THAT IS STATED RATHER THAN HIDDEN. Once
this upgrade runs, "which scar rows were originally context_context_bound" is
gone - the whole point of the collapse is that the distinction should not
have existed, so nothing recorded it separately for a downgrade to recover.
Downgrading widens the ENUM back so the value is legal again, but every row
this migration retiered stays `scar`. This is asymmetric with the pattern in
dwb584a1b2c3 (that downgrade drops the columns outright) only because this
column cannot be dropped without losing every memory in it; widening the enum
back is the least destructive downgrade available, not a full reversal.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb611a1b2c3"
down_revision: Union[str, Sequence[str], None] = "dwb605a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_FOUR_TIERS = sa.Enum(
    "raw", "core", "scar", "working", name="memorytier"
)
_FIVE_TIERS = sa.Enum(
    "raw", "core", "scar", "scar_context_bound", "working", name="memorytier"
)


def upgrade() -> None:
    # 1. Data first: retier every scar_context_bound row to scar. context_key
    #    is untouched (see module docstring) - only `tier` changes.
    op.execute(
        "UPDATE agent_memories SET tier = 'scar' WHERE tier = 'scar_context_bound'"
    )
    # 2. Narrow the ENUM now that nothing holds the value being removed.
    op.alter_column(
        "agent_memories",
        "tier",
        existing_type=_FIVE_TIERS,
        type_=_FOUR_TIERS,
        existing_nullable=False,
    )


def downgrade() -> None:
    # Widen the ENUM back so the value is legal again. Does NOT restore which
    # rows were originally scar_context_bound - see module docstring on why
    # that information is gone by design, not by oversight.
    op.alter_column(
        "agent_memories",
        "tier",
        existing_type=_FOUR_TIERS,
        type_=_FIVE_TIERS,
        existing_nullable=False,
    )
