# Path: alembic/versions/dwb605a1b2c3_journal_created_at.py
# File: dwb605a1b2c3_journal_created_at.py
# Created: 2026-09-30 (DWB-605)
# Purpose: journal_entries gains created_at - the memory's ORIGINAL insert
#          date, distinct from entered_at (the date it arrived in the
#          journal). Without this, moving a WORKING memory into the journal
#          on eviction (DWB-607) loses the date it was first written the
#          moment it moves, because entered_at is stamped at journal-arrival
#          time and would overwrite the only record of when the lesson
#          actually happened.
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb593a1b2c3
# Data Out: journal_entries.created_at
# Last Modified: 2026-09-30 (DWB-605)

"""journal_entries.created_at - original date vs journal-arrival date (DWB-605)

Revision ID: dwb605a1b2c3
Revises: dwb593a1b2c3
Create Date: 2026-09-30 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate is not
trusted here (spurious drop_index ops on error_logs, unreliable ENUM emission,
missed widenings).

FROM THE HUMAN MEMORY AUDIT, 2026-09-30: journal_entries today conflates two
different dates under one column. `entered_at` is stamped by
app/services/journal.py::create_entry at the moment a row is written, which is
correct for an entry a session writes directly - but DWB-607 (WORKING-floor
eviction) needs to journal a memory that was CREATED much earlier and is only
NOW arriving in the journal on its way out of agent_memories. Writing that
row today would stamp `entered_at` with the eviction moment and there would be
nowhere left to record when the lesson was actually learned.

`created_at` here is the memory's original date. `entered_at` keeps its
existing meaning (journal-arrival date) with zero behaviour change for every
row a session journals directly, where the two dates are the same day by
construction.

BACKFILL, PER PROJECT RULES ON ADDING A NOT NULL COLUMN TO A TABLE WITH
EXISTING ROWS: add the column NOT NULL with a server_default so MySQL can
satisfy the constraint at ADD-COLUMN time on every existing row, then an
explicit UPDATE overwrites that default with each row's own entered_at - the
best-effort answer the ticket calls for, since no better value exists for
anything already in the table (nothing recorded an original date before this
column existed). A server_default alone would leave every pre-existing row
reading a single fixed timestamp instead of its own history.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwb605a1b2c3"
down_revision: Union[str, Sequence[str], None] = "dwb593a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "journal_entries",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    # Backfill: every row that existed before this column did has no better
    # answer than its own entered_at (best-effort default, per the ticket -
    # nothing recorded an original date before now). New rows going forward
    # get their real created_at from the caller (app/services/journal.py).
    op.execute("UPDATE journal_entries SET created_at = entered_at")


def downgrade() -> None:
    op.drop_column("journal_entries", "created_at")
