# Path: alembic/versions/dwbg006a1b2c3_add_session_narrative.py
# File: dwbg006a1b2c3_add_session_narrative.py
# Created: 2026-06-25
# Purpose: Add dwb_sessions.narrative (JSON) + provenance columns (DWBG-006)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwb481a1b2c3
# Data Out: dwb_sessions.narrative + narrative_author + narrative_generated_at columns
# Last Modified: 2026-06-25

"""session narrative + provenance columns (DWBG-006)

Revision ID: dwbg006a1b2c3
Revises: dwb481a1b2c3
Create Date: 2026-06-25 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops and is not trusted.

P1 of the Session Recall Layer (Epic 4). The interpretive narrative the
deterministic `summary` (DWB-481) cannot produce - decisions, blockers,
next-steps - lives in a sibling column so the always-present summary baseline
is never touched or blocked:

- dwb_sessions.narrative: nullable JSON, same free-form shape as `summary` so
  the frontend can render both uniformly. Only set once a narrative is authored
  (TL inline at a conscious close, or async summarizer backfill).
- dwb_sessions.narrative_author: who produced it ('tl' | 'summarizer'). Plain
  VARCHAR rather than an enum so a future author kind needs no migration.
- dwb_sessions.narrative_generated_at: when it was produced.

All nullable; existing rows stay untouched (deterministic `summary` remains
their only write-up until re-synthesized).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwbg006a1b2c3"
down_revision: Union[str, None] = "dwb481a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # All nullable; no server_default needed (existing rows stay NULL).
    op.add_column(
        "dwb_sessions",
        sa.Column("narrative", sa.JSON(), nullable=True),
    )
    op.add_column(
        "dwb_sessions",
        sa.Column("narrative_author", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "dwb_sessions",
        sa.Column("narrative_generated_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("dwb_sessions", "narrative_generated_at")
    op.drop_column("dwb_sessions", "narrative_author")
    op.drop_column("dwb_sessions", "narrative")
