# Path: alembic/versions/dwbg010a1b2c3_add_session_search_text_fulltext.py
# File: dwbg010a1b2c3_add_session_search_text_fulltext.py
# Created: 2026-06-25
# Purpose: Add dwb_sessions.search_text (STORED generated column) + a FULLTEXT index for session-prose search (DWBG-010)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwbg006a1b2c3
# Data Out: dwb_sessions.search_text column + ftx_dwb_sessions_search FULLTEXT index
# Last Modified: 2026-06-25

"""session search_text generated column + FULLTEXT index (DWBG-010)

Revision ID: dwbg010a1b2c3
Revises: dwbg006a1b2c3
Create Date: 2026-06-25 00:00:00.000000

Hand-written, not autogenerated - per project rules, MySQL autogenerate emits
spurious drop_index ops and does not round-trip generated columns / FULLTEXT
indexes reliably.

P2 of the Session Recall Layer (Epic 4), search substrate (DWBG-002 spec).

MySQL cannot FULLTEXT-index a JSON column directly. So we add a STORED generated
column, `search_text`, that flattens the three prose-bearing fields - `headline`
(VARCHAR) plus `summary` and `narrative` (JSON, CAST to CHAR) - into one TEXT
blob via CONCAT_WS, then put an InnoDB FULLTEXT index on that column. Verified on
MySQL 8.0.46: InnoDB accepts a FULLTEXT index over a STORED generated column.

- dwb_sessions.search_text: nullable TEXT, GENERATED ALWAYS AS (...) STORED. The
  CONCAT_WS+COALESCE keeps it non-null even when individual fields are NULL.
  Read-only; never written by the app (MySQL maintains it from the base columns).
  Because it is STORED, existing rows are populated by MySQL at ALTER time, so
  no separate backfill is needed - the column materializes from the current
  headline/summary/narrative of every row.
- ftx_dwb_sessions_search: FULLTEXT index on search_text. The structural JSON
  keys (lead/sections/title/bullets) appear in every row, so MySQL
  natural-language mode treats them as low-IDF stopwords; search quality is
  driven by the distinctive prose, not the scaffolding.

The generated expression matches the ORM Computed() definition on
DwbSession.search_text byte-for-byte so the migration (dev DB) and
Base.metadata.create_all (lat_test) produce an identical schema.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "dwbg010a1b2c3"
down_revision: Union[str, None] = "dwbg006a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Kept in one place so upgrade()'s ADD COLUMN matches the ORM Computed() exactly.
# NULLIF(...,'null') collapses the JSON literal `null` (what SQLAlchemy stores
# for a Python None in a JSON column, which CAST renders as the string 'null')
# back to SQL NULL; CONCAT_WS then drops it, so an unsynthesized session has an
# empty search_text rather than "null null". See the model column comment.
_SEARCH_TEXT_EXPR = (
    "CONCAT_WS(' ', NULLIF(headline,''), "
    "NULLIF(CAST(summary AS CHAR),'null'), "
    "NULLIF(CAST(narrative AS CHAR),'null'))"
)


def upgrade() -> None:
    # Add the STORED generated column first; MySQL materializes it for every
    # existing row at ALTER time (no separate backfill needed). Raw SQL rather
    # than op.add_column(Computed(...)) so the generated expression is explicit
    # and the column lands before the FULLTEXT index that depends on it.
    op.execute(
        "ALTER TABLE dwb_sessions "
        "ADD COLUMN search_text TEXT GENERATED ALWAYS AS "
        f"({_SEARCH_TEXT_EXPR}) STORED"
    )
    # FULLTEXT index over the generated column.
    op.execute(
        "CREATE FULLTEXT INDEX ftx_dwb_sessions_search "
        "ON dwb_sessions (search_text)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX ftx_dwb_sessions_search ON dwb_sessions")
    op.execute("ALTER TABLE dwb_sessions DROP COLUMN search_text")
