# Path: alembic/versions/dwbg014a1b2c3_add_force_session_writeup.py
# File: dwbg014a1b2c3_add_force_session_writeup.py
# Created: 2026-06-25
# Purpose: Add projects.force_session_writeup boolean (DEFAULT TRUE) — the gate that
#          enables auto-generation of the LLM session wrap-up narrative on close (DWBG-014)
# Caller: alembic upgrade head
# Callees: alembic.op
# Data In: existing schema at dwbg010a1b2c3
# Data Out: projects.force_session_writeup column
# Last Modified: 2026-06-25

"""add projects.force_session_writeup (default ON) (DWBG-014)

Revision ID: dwbg014a1b2c3
Revises: dwbg010a1b2c3
Create Date: 2026-06-25 00:00:00.000000

Hand-written, not autogenerated — per project rules, MySQL autogenerate emits
spurious drop_index ops on error_logs.

P3 of the Session Recall Layer (Epic 4): the summarizer (DWBG-014) generates a
human-readable wrap-up narrative on session close. Generation is gated per
project by this flag, which DEFAULTS ON — the headline feature is on out of the
box, with an escape hatch to disable it (token-sensitive projects PATCH it off).

NOT NULL with a server_default of TRUE so existing project rows backfill to ON
at ALTER time. The default matches the ORM column default and the
ProjectCreate schema default (both True), so the migration (dev DB) and
Base.metadata.create_all (lat_test) produce an identical schema.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "dwbg014a1b2c3"
down_revision: Union[str, None] = "dwbg010a1b2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "projects",
        sa.Column(
            "force_session_writeup",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("1"),
        ),
    )


def downgrade() -> None:
    op.drop_column("projects", "force_session_writeup")
